### ISSUE TITLE
Setting generateId option not working anymore

### ISSUE THREAD

**Issue by nickschot** [fortunejs/fortune#100]
I pass the following to fortune:
```
fortune.create({
    adapter: {
        type: MongodbAdapter,
        options: {
            url: 'some_url',
            generateId: function(){
                return crypto.randomBytes(16).toString('hex');
            }
        }
    }
})
```
But the function is not correctly overwritten as it still generates the randomBytes when I create a document instead of using my function.

Fortune beta 38
Fortune-mongodb 1.0.1 and 1.0.2

**Comment by 0x8890** [comment]
Can you verify if this is a problem in Fortune or in the MongoDB adapter?
