### ISSUE TITLE
Correctly parse dasherized keys in JSON API serializer

### ISSUE THREAD

**Issue by nickschot** [fortunejs/fortune#101]
The JSON API spec *recommends* that member names be dasherized. It is allowed to use underscores and camelcased member names too. Currently when defining a type like `itemThing` only works if the JSON API payload references it as `itemThing` and not with `item-thing`.

Might it be an idea to add this recommendation as default in the JSON API serializer and/or make it (easily) configurable?

PS. This is no big trouble right now as things like ember make it very easy to change the serializer to camelize keys instead of dasherizing them. Might be a small bump for new people as it's not as plug & play with some of the big JSON API implementations.

See: http://jsonapi.org/recommendations/#naming

**Comment by 0x8890** [comment]
It's already an option, there's just not documentation on the website for it yet: https://github.com/fortunejs/fortune/blob/master/lib/serializer/serializers/json_api/settings.js#L42-L43

Currently it only affects record output, it should also affect record input as well. As always, PR is welcome.

**Comment by nickschot** [comment]
Ahh, didn't know that yet. Will take a look at it tomorrow.

**Comment by 0x8890** [comment]
Fixed in commit https://github.com/fortunejs/fortune/commit/f334f1c02f5aafd9944ed276a5be8e8f56ce039d.

**Comment by nickschot** [comment]
Yer very quick sir! :+1: Works great!
