### ISSUE TITLE
[JSON API] Multiple includes not working

### ISSUE THREAD

**Issue by nickschot** [fortunejs/fortune#102]
When issueing a request like: `/items?include=subitems,subitems.something` or `/items?include=subitems,otheritems` nothing gets included. `/items?include=subitems` works fine.

Meanwhile JSON API also states that a request like `/items?include=subitems.something` should include records for both `subitems` and `something`. Fortune currently only adds `something`.

See: http://jsonapi.org/format/#fetching-includes

**Comment by 0x8890** [comment]
Are you sure? There is a test for this: https://github.com/fortunejs/fortune/blob/master/test/integration/serializers/json_api.js#L197-L211

So I'm not sure if this is a problem.

**Comment by nickschot** [comment]
It might also have to do with ember data url encoding the comma. The stuff in the internal Fortune include array seems wrong (i.e. [[item,item],[subitem]] for item,item.subitem). I'll have time to look at it tomorrow again.

It indeed states in the greyish box that parent relationships should be included.

**Comment by 0x8890** [comment]
URI encoding seems highly likely to be the problem here, I'll investigate that, as well as a fix for the nested relationships.

**Comment by nickschot** [comment]
Yea, I checked some more examples where ember-data uses a comma in the request, and it always encodes it (which seen as it's a reserved character is expected I guess). I can test some more examples if you want and give you the structure of the include array (from the documentation it was not entirely clear how it should look).

**Comment by 0x8890** [comment]
@nickschot I've already come up with a fix, will push it and add test for it in a few moments, I'm a bit busy right now but the solution was to call `decodeURIComponent` within the serializer (fix #1) and to manually expand nested includes (fix #2).

**Comment by nickschot** [comment]
Excellent! Don't hurry for me! ;-)

**Comment by 0x8890** [comment]
Fixed in commit https://github.com/fortunejs/fortune/commit/abf205fc6c64542382faf7270cb3491a181ed91d.

**Comment by nickschot** [comment]
Trying it out now!

**Comment by nickschot** [comment]
Working excellently now. Nice fix.

**Comment by 0x8890** [comment]
:+1:
