### ISSUE TITLE
MySQL Support?

### ISSUE THREAD

**Issue by cmkornell** [fortunejs/fortune#103]
Is there any support for MySQL currently? I see there was a Fortune relational adapter on npm at one point, but I can't seem to find anything anymore. This library looks really great, btw.

**Comment by 0x8890** [comment]
There's a [Postgres adapter](https://github.com/fortunejs/fortune-postgres), which is highly specific to postgresql syntax. With a little tweaking it could work with MySQL I guess, it's just a matter of finding the differences in sql syntax.

**Comment by cmkornell** [comment]
Ok, thanks!

**Comment by JohnField** [comment]
I've started a fork of this with tweaking for MySQL - https://github.com/JohnField/fortune-mysql - much functionality doesn't work due to the Postgres specifics, but it's something am interested in looking into.
