### ISSUE TITLE
Errors while working with linked types

### ISSUE THREAD

**Issue by voronianski** [fortunejs/fortune#104]
I want to have 2 linked types in my app `card` and `word`. The basic relations between them are as follows - _one card can have many words inside, one word can be mentioned in many cards_. Here is how the code looks like:

```javascript
import http from 'http';
import Fortune from 'fortune';
import MongodbAdapter from 'fortune-mongodb';

const port = process.env.PORT || 9876;
const store = Fortune.create({
    adapter: {
        type: MongodbAdapter,
        options: {
            url: 'mongodb://localhost:27017/dev'
        }
    }
});
const server = http.createServer(Fortune.net.http(store));

store.defineType('card', {
    name: { type: String },
    words: { link: 'word', 'inverse': 'cards', isArray: true }
});
store.defineType('word', {
    romaji: { type: String },
    hiragana: { type: String },
    katakana: { type: String },
    cards: { link: 'card', 'inverse': 'words', isArray: true }
});

store.connect().then(() => {
    server.listen(port);
    console.log(`api is listening at http://localhost:${port}`);
});
```

Probably I assume something wrong, **but how can I actually I add `words` to a `card`?** 

For example while making request like:

```bash
PATCH http://localhost:9876/dXNlcnM 
# payload
{
    "@graph": [{
        "@type": "card",
        "id": "NSpAjoIu5Wy5D2XwNUzK",
        "name": "test",
        "words": []
    }]
}
```

returns a strange error:

```bash
{
  "@error": {
    "name": "BadRequestError",
    "message": "The value of \"words\" is invalid, it must be an array."
  }
}
```

**Comment by 0x8890** [comment]
See the example payload here: http://micro-api.org/#updating-records
And see the test case here: https://github.com/fortunejs/fortune/blob/master/test/integration/serializers/micro_api.js#L226-L244

Basically, a PATCH payload is more or less the same as a GET payload, so you need to wrap `id` in an object.

The error message should probably be more informative than what it currently is, thanks for reporting!

**Comment by voronianski** [comment]
@0x8890 so basically I need to create a `word` type first and then PATCH its' id in a object notation to `card` type and both of them will be linked, right?

**Comment by 0x8890** [comment]
@voronianski Your setup looks correct, here's what a payload would look like in your case:

```
PATCH /cards

{
  "@graph": [{
    "@type": "card",
    "id": "foo",
    "words": {
      "id": ["bar", "baz"]
    }
  }]
}
```

You could do this from either direction, by updating cards or words.

**Comment by voronianski** [comment]
@0x8890 thanks, I just tried the steps I've described with correct payload and it works fine. :+1: 

This also means that when PATCHing `words` with `id` they will be overwritten?

**Comment by 0x8890** [comment]
@voronianski yes, that is correct. If you want to work with arrays, you can use the `@operate` keyword. Micro API does not define the semantics for this, but Fortune.js implements it like so:

```js
{
  "@graph": [{
    "@type": "card",
    "id": 1,
    "@operate": {
      "push": { "words": ["foo", "bar"] },
      "pull": { "words": ["baz"] }
    }
  }]
}
```

**Comment by voronianski** [comment]
@0x8890 wow `@operate` looks nice, haven't seen that in docs :/

**Comment by 0x8890** [comment]
@voronianski yup it's intentionally a bit undocumented/underspecified right now, but I'm working on a new website / more docs which should make it much more clear :)

**Comment by voronianski** [comment]
@0x8890 super cool! :sunglasses: thanks once again!

**Comment by voronianski** [comment]
@0x8890 btw how stable is fortunejs (as well as micro-api)? I noticed some api changes from the time I played with it last time one month ago.

**Comment by 0x8890** [comment]
@voronianski I will be pushing RC1 of Fortune.js soon, only small fixes. The only reason why it's not `1.0` yet is that there may still be some bugs in the included serializers, but the core is pretty stable. Micro API should be locked down after the last update, which was just using the `@graph` keyword from JSON-LD. 

Out of curiosity, why did you decide to go with Micro API instead of JSON API?

**Comment by voronianski** [comment]
@0x8890 thanks, it's also about curiosity and exploration. I like the simplicity and rules that micro api provides and together with fortune (as it throws away a lot of boilerplate) it looks like ideal candidate for an api of my small pet project :)
