### ISSUE TITLE
How to handle custom find parameters for collections?

### ISSUE THREAD

**Issue by joostfarla** [fortunejs/fortune#106]
When querying a collection, is it possible to implement custom handling logic like:
- Map parameter names to DB property names, when not equal
- Perform a regex find, based on parameter value
- Perform a geo-search, based on lat and long parameters
- Throw errors when multiple parameters are given, which cannot be used in conjunction

It would be nice to be able to implement some kind of proxy method for the query object. I'm using MongoDB for storage, but I guess this is relevant for all storage plugins.

**Comment by 0x8890** [comment]
It is left entirely up to the specific adapter to support anything that isn't specified in the Adapter base class. 

If you are using the MongoDB adapter you can use the `query` option which will accept arbitrary MongoDB queries.

https://github.com/fortunejs/fortune-mongodb/blob/master/lib/index.js#L63-L64

```js
store.request({
  type: 'user',
  options: {
    query: { ... } // arbitrary mongodb query
  }
})
```

**Comment by joostfarla** [comment]
Thanks for your quick reply!

If I understand your answer correctly, the `query` option is meant to provide some initial query object for find operations for (in this case) Mongo. However, that does not solve all cases. What I meant is being able to handle custom conditions, like the following:

```js
if (req.query.lat && req.query.long) {
  query['geo'] = { $geoWithin : { $box : [[ req.query.long , req.query.lat ], [ 100, 100 ]] }}
}

if (req.query.lat && !req.query.long) {
  // throw some custom error
}
```

Since the `query` option is a plain JS object and not a function, I don't think this can be achieved at this moment?

**Comment by 0x8890** [comment]
Ah, I see what you mean. If this is intended to be generic, you could subclass the MongoDB adapter like so:

```js
import fortune from 'fortune'
import mongodbAdapter from 'fortune-mongodb'

const { Adapter } = fortune

// Dependency injection function.
const MongodbAdapter = mongodbAdapter(Adapter)

class CustomAdapter extends MongodbAdapter {
  find (type, ids, options) {
    // Do request validation logic here.
    return super(...arguments)
  }
}
```

I think that's what you're trying to do.

**Comment by joostfarla** [comment]
Thanx! For generic cases this should work! Any idea to do the same for specific types?

**Comment by 0x8890** [comment]
Same idea:
```js
class ApplicationAdapter extends MongodbAdapter {
  find (type, ids, options) {
    // Any validation logic could be here.
    if (type === 'user') { ... }
    return super(...arguments)
  }
}
```

**Comment by nnnnathann** [comment]
Just to expand on this a little bit,  I have been handling this in a way that delegates what are typically adapter responsibilities to a series of resource classes inheriting from an abstract class that does the typical adapter stuff by default i.e.


```js
import di from '../../di';
import requireDir from 'require-dir';

let resources = requireDir('../resources');

export default Adapter => class DashboardsAdapter extends Adapter {
    connect() {
        this.r = di.container.rethinkdb.r;
        return di.container.rethinkdb.promise.then( connection => {
            this.connection = connection;
        });
    }

    disconnect() {
        let out;
        try {
            this.connection.close();
            out = Promise.resolve();
        } catch(error) {
            out = Promise.reject(error);
        }
        return out;
    }

    getResourceInstance(type) {
        if (resources[type]) {
            let Resource = resources[type].default;
            return new Resource(this.r, this.connection);
        }
    }


    find(type, ids, options = {}) {
        if (ids && !ids.length) return super.find();
        return this.getResourceInstance(type).find(ids, options);
    }

    create(type, records) {
        if (!records.length) return super.create();
        return this.getResourceInstance(type).create(records);
    }

    update(type, updates) {
        if (!updates.length) return super.update();
        return this.getResourceInstance(type).update(updates);
    }

    delete(type, ids) {
        return this.getResourceInstance(type).delete(ids);
    }
}
```

hope that helps!


thanks to @0x8890 for this library, really scratching an itch

**Comment by 0x8890** [comment]
@nnnnathann do you mind sharing your RethinkDB adapter at some point? :)

**Comment by nnnnathann** [comment]
Sure, I can do that, will work on a more abstracted out version thats not so specific to my app

In my use case almost all resources are permissions controlled by session user so theres a lot of junk in there that isn't strictly standard, but I'll pull it out for ya
