### ISSUE TITLE
Subscribing to store changes

### ISSUE THREAD

**Issue by unindented** [fortunejs/fortune#108]
Say I have a RESTful API where clients GET and POST resources, but I want to notify all clients through websockets when a record of a certain type gets created. How would I go about subscribing to certain changes in the store?

**Comment by 0x8890** [comment]
recently there is the `fortune.net.websocket` function, which will create a websocket server. internally it uses `ws` so look there for docs. the third argument `change` is probably what you're interested in, you will need to override it. see:https://github.com/fortunejs/fortune/blob/master/lib/net/websocket.js

using this is completely optional, if you want to use another websocket implementation you can listen for the change event on the fortune instance.

**Comment by unindented** [comment]
It's all in the docs, why didn't I read them properly!?

Thank you!
