### ISSUE TITLE
`change` handler receives empty record

### ISSUE THREAD

**Issue by unindented** [fortunejs/fortune#109]
The `change` handler I'm passing to `fortune.net.websocket` receives an empty record when POSTing:

```js
var wss = fortune.net.websocket(store, options, function (socket, evt) {
  var created = evt[fortune.methods.create];
  if (created) {
    console.log(created); // {user: [undefined]}
  }
});
```

From what I see, the reason is that this piece of code (https://github.com/fortunejs/fortune/blob/f6e17b9b6d74484df2f4e9877d3957d5ae10df57/lib/dispatch/create.js#L112-L114) maps `(record) => record.id`, but my records at that point don't have an `id` field.

I POSTed the following:

```js
{
  "@graph": [{
    "@type": "user",
    "firstName": "John",
    "lastName": "Doe",
    "jobTitle": "Developer"
  }]
}
```

And the record before mapping looks like this:

```js
{
  "firstName": "John",
  "lastName": "Doe",
  "jobTitle": "Developer"
}
```

Am I doing something wrong?

**Comment by 0x8890** [comment]
This is possibly a bug, will investigate.

**Comment by 0x8890** [comment]
It was indeed a bug, fixed in commit https://github.com/fortunejs/fortune/commit/749dc31a9e093fc29d44af00cadc87973ee6c41e.

**Comment by unindented** [comment]
Awesome! Thank you @0x8890.
