### ISSUE TITLE
Can't seed initial data

### ISSUE THREAD

**Issue by ivan-kleshnin** [fortunejs/fortune#110]
```js
let store = Fortune.create({
  serializers: [{
    type: Fortune.serializers.JSONAPI,
  }]
});

store.defineType("user", {
  name: {type: String},
  groups: {link: "group", inverse: "members", isArray: true}
});

store.defineType("group", {
  name: {type: String},
  members: {link: "user", inverse: "groups", isArray: true}
});

// Trying to do this:
store.adapter.create("user", [
  {id: "1", name: "Foo", groups: []},
  {id: "2", name: "Bar", groups: []},
]).catch(errors => {
  console.log(errors); // logs [TypeError: Cannot read property 'user' of undefined] ???
});
```

The only example I found at https://github.com/fortunejs/fortune/blob/master/test/unit/adapter.js seems in line with what I do.

**Comment by 0x8890** [comment]
Looks like you forgot to call `connect` before doing stuff :)

FYI, `adapter` is supposed to be a pseudo-private property, avoid it and use `request` method instead. It's not meant to be used directly because then you'd have to provide denormalized records and it bypasses referential integrity checking.

**Comment by ivan-kleshnin** [comment]
> Looks like you forgot to call connect before doing stuff :)

Yes, good catch. 

> FYI, adapter is supposed to be a pseudo-private property, avoid it and use request method instead. It's not meant to be used directly because then you'd have to provide fully denormalized fields and it bypasses referential integrity checking.

You mean http://fortunejs.com/api/#fortune-request 
e.g. approach this via an emulation of HTTP requests?!

**Comment by 0x8890** [comment]
The `request` method has nothing to do with HTTP actually, despite what the name may sound like, and it maps cleanly to the adapter methods. The advantage of using the `request` method is that it will do referential integrity checking, handle relationship updates, and run transform functions. Unless of course you are 100% certain that your fixture data is correct, it's the recommended way to go.
