### ISSUE TITLE
Error "The serializer must be a function or class"

### ISSUE THREAD

**Issue by unindented** [fortunejs/fortune#115]
I went from `1.0.0-rc7` to `1.0.0` today, and found that my small example app had stopped working with this error.

I guess it has to do with these lines: https://github.com/unindented/fortune-example/blob/master/server/store.js#L7-L14

But I'm not sure how to achieve that same result with `1.0.0`...

**Comment by 0x8890** [comment]
There was a big breaking change: there are no longer vendor-specific serializers included, they have moved to separate modules now. It's documented [here](https://github.com/fortunejs/fortune/blob/master/doc/CHANGELOG.md).

The module you're looking for is [here](https://github.com/fortunejs/fortune-micro-api).

**Comment by unindented** [comment]
Cool, thanks!
