### ISSUE TITLE
Error in mongodb adapter

### ISSUE THREAD

**Issue by emmenko** [fortunejs/fortune#118]
Works with `fortune@1.0.1` and `fortune-mongodb@1.0.5`. With latest versions I get this error

```bash
error: TypeError: Cannot use 'in' operator to search for 'match' in null
    at MongodbAdapter.find (/app/node_modules/fortune-mongodb/dist/index.js:95:26)
    at /app/node_modules/fortune/dist/lib/dispatch/include.js:132:51
    at run (/app/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /app/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/app/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:9:13)
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by 0x8890** [comment]
This is the wrong repository to report this error, should [open the issue here](https://github.com/fortunejs/fortune-mongodb).

**Comment by 0x8890** [comment]
By the way, it's related to a bug in Babel I think. https://github.com/fortunejs/fortune/pull/117

**Comment by emmenko** [comment]
I was going to but the error happened when I upgraded fortune version, that's why I opened it here.

But anyway, the important thing is that we fix the problem :)

**Comment by 0x8890** [comment]
Fixed in commit https://github.com/fortunejs/fortune-mongodb/commit/9f80bdec174ca7fbaf8fb1c1d5f724625d02bf71
