### ISSUE TITLE
post fail

### ISSUE THREAD

**Issue by 1STi** [fortunejs/fortune#124]
Hi, using the example i'm sending the post data:

{
    "data": {
        "type": "users",
        "attributes": {
            "name": "Igor"
        }
    }
}

and get the response:

{
  "name": "BadRequestError",
  "message": "Payload is empty."
}

I've tried a number of posts formats with no luck.

Thanks for any help.

**Comment by thibremy** [comment]
You use json-api ?
Don't forget to add this serializer.

    import JsonApi from 'fortune-json-api';

    const store = fortune.create({
      serializers: [{
        type: JsonApi
      }]
    });


Take a look at [JSON-API RFC](http://jsonapi.org/format/#crud)

    Content-Type: application/vnd.api+json // Don't Forget this headers
    Accept: application/vnd.api+json
    {
      "data": {
        "attributes": {
          "name": "john",
        },
        "type": "users"
      }
    }

With supertest/super-agent you can do something like that:

    request.post('/api/users')
      .set('Content-Type', 'application/vnd.api+json')
      .set('Accept', 'application/vnd.api+json')
      .send(JSON.stringify({
          data: {
            type: 'users',
            attributes: {
              username: 'myusername',
              role: 'administrator',
              password: '1234',
            },
          },
        })
      .expect(200);

**Comment by 0x8890** [comment]
thanks @thibremy for the answer, said it better than I would have :)

**Comment by 1STi** [comment]
Thanks for the reply guys.

Unfortunately, still no luck. I made the changes and set the post of the two suggested ways and nothing.

My server code:

import fortune from 'fortune';
import JsonApi from 'fortune-json-api';
import http from 'http';

const store = fortune.create({
  serializers: [{
    type: JsonApi
  }]
});

// The `net.http` function returns a listener function which does content
// negotiation, parses headers, and maps the response to an HTTP response.
const server = http.createServer(fortune.net.http(store));

store.defineType('user', {
  name: { type: String },

  // Following and followers are inversely related (many-to-many).
  following: { link: 'user', inverse: 'followers', isArray: true },
  followers: { link: 'user', inverse: 'following', isArray: true },

  // Many-to-one relationship of user posts to post author.
  posts: { link: 'post', inverse: 'author', isArray: true }
});

store.defineType('post', {
  message: { type: String },

  // One-to-many relationship of post author to user posts.
  author: { link: 'user', inverse: 'posts' }
});

store.connect().then(() => server.listen(1337));
console.log('Server running at localhost: 1337');

My post data (with correct headers):

{
  "data": {
    "attributes": {
      "name": "john",
    },
    "type": "user"
  }
}

The response:

{
  "errors": [
    {
      "title": "Error",
      "detail": "An internal server error occurred."
    }
  ]
}

My packages.json:

{
    "name": "teste",
    "description": "teste",
    "version": "0.0.1-dev",
    "scripts": {
        "babel-node": "babel-node"        
    },
    "dependencies": {		
        "fortune": "1.3.2",
        "fortune-json-api": "1.1.5"
	}
}

**Comment by 1STi** [comment]
Complete post-data:

POST /users HTTP/1.1
Host: localhost:1337
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json
Cache-Control: no-cache
Postman-Token: b050bc68-9531-b4e3-f495-07c991a88854

{
  "data": {
    "attributes": {
      "name": "john",
    },
    "type": "users"
  }
}

PS: I can get with no problem.

**Comment by 0x8890** [comment]
Hmm, what is the error? You can debug by replacing this line:

```js
 const server = http.createServer(fortune.net.http(store))
```

With this:

```js
const server = http.createServer(function () {
  fortune.net.http(store)(...arguments)
  .catch(error => console.error(error.stack))
})
```

I should consider adding a `debug` flag to output errors to console.

**Comment by thibremy** [comment]
With JSON-API you have to 'pluralize' your type.
{
  "data": {
    "attributes": {
      "name": "john",
    },
    "type": "users" // don't forget
  }
}

Take a look at this [gist](https://gist.github.com/thibremy/7fb51bdbf5012b88337e) .

**Comment by 1STi** [comment]
SyntaxError: Unexpected token }
    at Object.parse (native)
    at JsonApiSerializer.initializeContext (/resources/node_modules/fortune-json-api/dist/lib/helpers.js:92:64)
    at JsonApiSerializer.processRequest (/resources/node_modules/fortune-json-api/dist/lib/index.js:99:43)
    at SerializerSingleton.proxyMethod (/resources/node_modules/fortune/dist/lib/serializer/singleton.js:183:64)
    at /resources/node_modules/fortune/dist/lib/dispatch/index.js:87:27
    at run (/usr/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:89:39)
    at /usr/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/lib/node_modules/babel/node_modules/babel-core/node_modules/core-js/modules/$.microtask.js:17:13)
    at process._tickDomainCallback (node.js:381:11)

**Comment by 0x8890** [comment]
Look at this line in your input:
```
"name": "john",
```
Drop the comma :)

**Comment by 1STi** [comment]
Nice, was the comma typo!!! Thank you very much!

I'm starting using it today!!!

**Comment by 1STi** [comment]
The debug option was very helpful, indeed.

**Comment by 0x8890** [comment]
You're welcome, I will open a new issue for that :)
