### ISSUE TITLE
What's the JWT story with Fortune?

### ISSUE THREAD

**Issue by wayne-o** [fortunejs/fortune#125]
Has anyone done any work on this or is there any guidance?

Cheers

**Comment by 0x8890** [comment]
I assume you mean JSON Web Tokens? I'm not too familiar on this topic, but why not use this library: https://github.com/auth0/node-jsonwebtoken

Any sort of authorization scheme is business logic, and won't be handled by this library. Here's how you could generically handle authorization checks in Node.js:

```js
import fortune from 'fortune'
import http from 'http'

const store = fortune.create()
const listener = fortune.net.http(store)

http.createServer((request, response) => {
  if (request.headers['authorization'] !== 'foobar') {
    response.statusCode = 401
    return response.end()
  }
  return listener(request, response)
}).listen(1337)
```

It's just not within the scope of this project to implement authorization.

**Comment by wayne-o** [comment]
OK thank you

**Comment by thibremy** [comment]
Fortune is not an oauth server or authorizer.

If you use express/koa, you have to implement your own auth/acl stack, take a look at [oauth2orize] (https://github.com/jaredhanson/oauth2orize).

After that you can wrap fortune.net into a middleware.
