### ISSUE TITLE
Consider removing Babel

### ISSUE THREAD

**Issue by 0x8890** [fortunejs/fortune#129]
With the release of Node 4.0, most ES6 features are built-in to the V8 VM.

- Use CommonJS `require` instead of `import`/`export`
- ~~Avoid `class` keyword and go back to using `prototype`~~ (may not be necessary). this may bring better performance by avoiding `Object.setPrototypeOf`.
- Avoid spread operator, rest parameters, destructuring, default parameters (not fun but acceptable).

On the browser side, this would break things for all but the latest browsers but only due to browser support for ES6, perhaps it should be up to the consumer to transpile.

### ES6 features to use

These features are in Node 4.0 now and should also work in Chrome/Firefox.

- Object literal extensions
- for...of
- template strings
- const, let, block scope
- arrow functions
- Map, Set, WeakMap
- Promise
- Symbol
- Object.assign, Object.getOwnPropertySymbols
- ~~Array.prototype.find, Array.prototype.includes~~ not yet :(

**Comment by jlcarvalho** [comment]
+1

The babel-node debug on WebStorm has a lot of bugs.

**Comment by 0x8890** [comment]
I think I should wait on this, I'm not sure if I want to spend the effort into removing stuff which will hopefully soon be natively supported by the Node.js runtime in v5. however I am pretty frustrated with debugging transpiled code, and the [performance impact](http://www.incaseofstairs.com/2015/06/es6-feature-performance/) it has, which is rather important for running on servers with constrained resources (embedded, shared hosting, etc).

**Comment by 0x8890** [comment]
Perhaps it should go lower: ES5. This should allow for painless browser use and avoids many [performance pitfalls of ES6](https://kpdecker.github.io/six-speed/).

**Comment by kketch** [comment]
I think that you should stick with babel right now, this is one of things I personally love about fortune (not that it is using babel, but that it is written in ES6), node 4 has just been released and performance will get better over time. Of course there might be some unfortunate side effects to the use of babel in fortune, @jlcarvalho refer to bugs on WebStorm with babel-node, I assume we can expect these problems to go away.

There will be a significant amount of work to migrate from ES6 to ES5 (and from ES5 to ES6 back again later), why not wait for the day you can drop babel because ES6 is ready on the platforms you want to support ?
Also I don't see the browser use of fortune as a priority personally, not doing this will may allow you to focus on more relevant matters. Even with the performance argument, to me its seems that fortune will go backward

**Comment by 0x8890** [comment]
@kketch I am actually using Fortune in the browser so it is a concern, and running on resource-constrained servers so performance does matter. Some ES6 features are an order of magnitude slower. That is because typically the standard implementation covers many edge cases which will not be reached in most use cases. This is true even for ES5 i.e. `forEach` is slower than `for` or `while` loop. Even when the native implementations land, they can be much slower than userland implementations (see native Promise vs Bluebird). Regarding `class`, Fortune makes use of `super` which is slow across the board (unless in non-standards-compliant mode).

Up until now I haven't really thought of performance matters, so it would be a good place to start by writing optimized ES5 that is cross-platform compatible out of the box right now, and it would simplify debugging too. Developer experience must take a backseat to user experience, and I think that a ES5 refactor will bring easier debugging and a performance boost.

**Comment by passcod** [comment]
As long as the `class`es (or corresponding future structures) are still properly defined so as to be extendable in native ES6 code. I have seen various libraries use custom "class" wrappers that break ES6 extension, and they're a pain.

**Comment by 0x8890** [comment]
@passcod don't worry, ES6 classes are merely syntactic sugar. i.e. this code works without a problem, even though Node's internal classes are in ES5:
```js
const EventEmitter = require('events').EventEmitter
class Foo extends EventEmitter {}
```

**Comment by passcod** [comment]
Indeed, but e.g. [Bookshelf](http://bookshelfjs.org/)'s "classes" break if you try to extend them in ES6. Care has to be taken not to accidentally break the semantics, so I made that note/comment.

**Comment by 0x8890** [comment]
Done, codebase is now written in ECMAScript 5.1.
