### ISSUE TITLE
Bulk inserts

### ISSUE THREAD

**Issue by jlcarvalho** [fortunejs/fortune#131]
Like described in the **[bulk](http://jsonapi.org/extensions/bulk/)** extension of JSON API, is in the roadmap?

**Comment by 0x8890** [comment]
This should go in this [Fortune JSON API](https://github.com/fortunejs/fortune-json-api) issues. There are no plans for supporting extensions, and consider that there is no official support.

However if you want to, you can use the ad hoc json serializer or micro api to do bulk creates and updates.
