### ISSUE TITLE
Gather requirements for next-generation adapter

### ISSUE THREAD

**Issue by 0x8890** [fortunejs/fortune#132]
While relational and document databases work, they take a bit of effort to abstract the differences between them. The most natural fit for Fortune may be graph database, which is particularly well suited for inverse relationships.

### PostgreSQL / relational limitations:
- Since join tables cannot be defined within the Postgres adapter, and array foreign keys aren't supported, Fortune has to manually maintain inverse relationships.

### MongoDB / NoSQL limitations:
- While schema-less is a nice option, it's delegating the schema to the application layer (Fortune).
- No foreign key support, Fortune has to manually maintain inverse relationships.

With a graph database, Fortune doesn't have to do any extra work to maintain inverse relationships. The big problem is which one to evaluate. Neo4j seems to be the most popular option, but lack of a binary protocol is a big turn-off.

**Comment by hden** [comment]
An [API adaptor](https://github.com/brikteknologier/seraph) and [model layer](https://github.com/brikteknologier/seraph-model) is available for Neo4j. On the other hand, an embedded low-level storage (Graph Database on top of leveldb) is also available as [LevelGraph](https://github.com/mcollina/levelgraph).

**Comment by 0x8890** [comment]
Seraph looks promising, still uses http protocol though. LevelGraph is interesting but I think it's possible to just go lower and use LevelUP, since Fortune solves the problems of trying to use non-graph storage in a graph-like manner. That said, LevelDB seems to be a promising embedded database.

**Comment by passcod** [comment]
Why not leave it to a SQL-type ORM to do the job of maintaining inverse relationships etc? I'm currently writing a adapter for our own mysql database, using Bookshelf and Knex, and there's been no pain points apart from the lack of documentation for implementing Fortune Adapters (had to read the source a lot).

**Comment by 0x8890** [comment]
@passcod FYI there's a [Postgres adapter](https://github.com/fortunejs/fortune-postgres) that may fit your needs if you're not tied to MySQL, otherwise the syntax could simply be tweaked to support MySQL.

There's also a [project](https://github.com/0x8890/imagenote) that uses it.

**Comment by passcod** [comment]
Saw that, I am tied to it, and I'd also like to support "virtual fields" and other abstractions so I went with a custom adapter.

**Comment by 0x8890** [comment]
Oh I forgot to answer your question, why not defer to an ORM to maintain inverse relationships?

Fortune tries to abstract the DB and even implements its own in-memory database as default, and wraps around IndexedDB and Web Storage in the browser. Many databases don't support relations such as MongoDB so this has to be implemented by Fortune.

Also I'm not sure if it makes sense to use an ORM to implement an adapter, it's adding on two separate abstractions. The Postgres adapter uses only a driver and generates SQL queries manually.

**Comment by 0x8890** [comment]
After giving this some more thought, I think that using a graph database would be more trouble than its worth, since there is some overlap between what Fortune.js does and what a graph db does.
