### ISSUE TITLE
Array invalid as type Object

### ISSUE THREAD

**Issue by nickschot** [fortunejs/fortune#134]
The API states the following for a type Object: Note that the Object type should be a JSON serializable object that may be persisted. 

I'm creating/saving a record with the following JSON API payload:
```
{
    "data": {
        "attributes": {
            "answers": [
                "option2",
                "banana"
            ]
        },
        "relationships": {
            "logic": {
                "data": {
                    "type": "logic",
                    "id": "1dfcd53c053161128ee01f6376120f2a"
                }
            }
        },
        "type": "actions"
    }
}
```

My type is defined as:
```
export default store.defineType('action', {
    logic: {link: 'logic', inverse: 'actions'},

    answers: {type: Object}
});
```

As arrays are JSON serializeable, this should work fine (and always did with older fortune versions, not sure when it broke). The save goes fine when I replace the array with an empty object or an empty array.

EDIT: and of course the error message thrown by the server: `{"errors":[{"title":"BadRequestError","detail":"The request is malformed."}]}`

**Comment by 0x8890** [comment]
Hmm, this seems like it's a problem with the JSON API serializer.

**Comment by 0x8890** [comment]
Actually the error is correct. What you want is actually an array of strings:

```
answers: { type: String, isArray: true }
```

It should also throw an error if you pass an object literal instead of an array.

**Comment by nickschot** [comment]
That explains, thanks! I used the Object type as kind of a black box to throw in data I didn't need the server to do anything with but save.
