### ISSUE TITLE
Hopefully this is just me!

### ISSUE THREAD

**Issue by andrewcashmore** [fortunejs/fortune#138]
http://stackoverflow.com/questions/33263695/getting-started-with-fortunejs

**Comment by 0x8890** [comment]
I will copy my answer from StackOverflow:



It seems that the actual error message needs to be relayed to the client. You can do so by attaching a catch to the HTTP listener:

```js
const server = http.createServer((request, response) =>
  fortune.net.http(store)(request, response)
  .catch(error => console.log(error.stack)))
```

What I found when I recreated the steps was this:

```
Error: A related record for the field "author" was not found.
```

However, since it is a generic Error and not a typed error that Fortune uses internally, it is hidden from the client.

So by setting the correct value for the author id, it was able to create a record with that association successfully.

Future versions will be patched so that this informative error message gets shown.

**Comment by 0x8890** [comment]
p.s. it seems that your question doesn't fit the stackoverflow format.

**Comment by andrewcashmore** [comment]
Hi,

The related record error wasn't the one I was seeing. It was a `[TypeError: Cannot set property 'user' of undefined]` error message.

Cheers,
Andy

**Comment by 0x8890** [comment]
Just to be super clear, here's the request I made:
```
curl -i -X POST \
  -H "Content-Type: application/vnd.api+json" \
  -d '{"data":{"type":"posts","attributes":{"message":"This is my first post"},"relationships":{"author":{"data":{"type":"users","id":"7a8a27fb"}}}}}' \
  http://localhost:1337/posts
```
And what I got back was a 201 Created:
```
HTTP/1.1 201 Created
Content-Type: application/vnd.api+json
Connection: keep-alive
Location: http://localhost:1337/posts/ea6f3412
Content-Length: 348
Date: Wed, 21 Oct 2015 19:34:01 GMT

{"data":{"type":"posts","id":"ea6f3412","attributes":{"message":"This is my first post"},"relationships":{"author":{"links":{"self":"http://localhost:1337/posts/ea6f3412/relationships/author","related":"http://localhost:1337/posts/ea6f3412/author"},"data":{"type":"users","id":"7a8a27fb"}}},"links":{"self":"http://localhost:1337/posts/ea6f3412"}}}
```

I could not reproduce the error you got.

**Comment by andrewcashmore** [comment]
Weird, doing the exact same request and using your CURL but obviously replacing the Author ID and I'm getting this:

```
HTTP/1.1 500 Internal Server Error
Content-Type: application/vnd.api+json
Connection: keep-alive
Content-Length: 76
Date: Wed, 21 Oct 2015 19:41:15 GMT

{"errors":[{"title":"Error","detail":"An internal server error occurred."}]}
```

**Comment by andrewcashmore** [comment]
![tinygrab screen shot 21-10-2015 20 42 42](https://cloud.githubusercontent.com/assets/2070924/10648151/c7cc26e8-7834-11e5-9468-6a3ff2c13215.png)

**Comment by 0x8890** [comment]
It may come down to the Node.js version and/or Babel version you're using. FYI, Babel is not required to use Fortune, and I was able to run your example without Babel with one minor tweak (`import` -> `require`).

**Comment by andrewcashmore** [comment]
Okey dokes :) can I ask what version you're using? I'll remove the import stuff for now! :) I really appreciate your help.

**Comment by 0x8890** [comment]
I'm using Node v4.1.2 on Mac OS X 10.10 at the moment.

**Comment by andrewcashmore** [comment]
Literally just node version, I'm not sure wether to cry or smile ;) haha

**Comment by andrewcashmore** [comment]
Thank you, so, so much for your help.

**Comment by 0x8890** [comment]
Really? What version of Node.js were you using? If you had problems with your Node version I better update the `engine` version in the package.

**Comment by andrewcashmore** [comment]
The error occurred on v0.10.40 I just upped it all the way to v4.2.1

**Comment by andrewcashmore** [comment]
Unless it was the version of babel-node maybe :-/ that was 5.8.23

**Comment by 0x8890** [comment]
That's a really old version, currently in the `package.json` it lists `>=0.12`, so you should have seen a warning!

**Comment by andrewcashmore** [comment]
Yeah I didn't see a warning so I'm guessing it's actually a problem with babel-node rather than node itself.
