### ISSUE TITLE
How store float number

### ISSUE THREAD

**Issue by diogoazevedos** [fortunejs/fortune#139]
Hi @0x8890,

I need store float number like 100.88, how can I do that?

```js
module.exports = fortune.create()

.defineType('product', {
  title: { type: String },
  price: { type: Number } // should be a float
})
```

Thanks,
Diogo A.

**Comment by 0x8890** [comment]
In JavaScript, `Number` type always means double precision floating point. There's nothing more that you have to do here.

**Comment by diogoazevedos** [comment]
Hi @0x8890,

I make a request like:
```json
{
  "data": {
    "type": "products",
    "attributes": {
      "title": "iPhone 6s",
      "price": 100.88
    }
  }
}
```

But the response is like:
```json
{
  "data": {
    "type": "products",
    "id": "IzKL/kn6XGD3ImaF4zOs",
    "attributes": {
      "title": "iPhone 6s",
      "price": 100
    },
    "links": {
      "self": "http://localhost:1337/products/IzKL%2Fkn6XGD3ImaF4zOs"
    }
  }
}
```

If I change cast_value.js at line 5 to `parseFloat` from `parseInt`, works like a charm:
```json
{
  "data": {
    "type": "products",
    "id": "IzKL/kn6XGD3ImaF4zOs",
    "attributes": {
      "title": "iPhone 6s",
      "price": 100.88
    },
    "links": {
      "self": "http://localhost:1337/products/IzKL%2Fkn6XGD3ImaF4zOs"
    }
  }
}
```

This is an problem or it's working like expected?

Thanks,
Diogo A.

**Comment by 0x8890** [comment]
oops! that is a bug. can you send a PR?

On Oct 23, 2015 7:15 PM, "Diogo Azevedo" <notifications@github.com> wrote:
>
> Hi @0x8890,
>
> I make a request like:
>
> {
>   "data": {
>     "type": "products",
>     "attributes": {
>       "title": "iPhone 6s",
>       "price": 100.88
>     }
>   }
> }
>
> But the response is like:
>
> {
>   "data": {
>     "type": "products",
>     "id": "IzKL/kn6XGD3ImaF4zOs",
>     "attributes": {
>       "title": "iPhone 6s",
>       "price": 100
>     },
>     "links": {
>       "self": "http://localhost:1337/products/IzKL%2Fkn6XGD3ImaF4zOs"
>     }
>   }
> }
>
> If I change cast_value.js at line 5 to parseFloat from parseInt, works
like a charm:
