### ISSUE TITLE
Cannot call a class as a function

### ISSUE THREAD

**Issue by organic-scholar** [fortunejs/fortune#141]
```javascript
var fortune = require('fortune');
var jsonApi = require('fortune-json-api').default;
var http = require('http');

var store = fortune.create({
    serializers: [ {
        type: jsonApi
    }]
});
```
Following code throws error 'Cannot call a class as a function'

**Comment by 0x8890** [comment]
Thanks for reporting, there seems to be some issue with ES6 class compatibility. I tried to fix it in this commit https://github.com/fortunejs/fortune/commit/ad953f2f56f8c69dbdccddf631d9496bfaff429f. Can you confirm that it works again?

**Comment by organic-scholar** [comment]
Now its working thanks for quick fix.
