### ISSUE TITLE
how does this compare to loopback

### ISSUE THREAD

**Issue by coderofsalvation** [fortunejs/fortune#146]
$ npm install loopback
     $ du --summarize -H node_modules/
     31M     node_modules/
     $ rm -rf node_modules; npm install fortune
     2.6M    node_modules/

What could explain this huge difference?

**Comment by 0x8890** [comment]
Loopback has different goals than Fortune.js, it's a framework, and Fortune.js is more focused on connecting data sources, which includes handling different formats. 

One key difference is that Loopback expects you to use their provided SDKs and their *ad hoc* JSON-over-HTTP format, while Fortune.js does not favor any particular format and has support for hypermedia media types, you can even emit HTML if you want.

The second key difference is that Loopback is coupled with HTTP, it even includes `express` as a dependency. It gets you thinking in terms of RPC-style "endpoints", while Fortune.js is independent from any network protocol, though it is well-suited for HTTP. This makes it easier to work with Web Sockets, or even your own wire protocol.

Things Loopback has which Fortune.js is not concerned with:
- Client SDKs
- GUI for management
- API gateway

Things Fortune.js does that Loopback doesn't:
- Multiple serialization formats, necessary for content negotiation and human-driven hypermedia (HTML).
- Ease of use over any network protocol. Fortune.js provides an HTTP wrapper function which is only ~150 LOC.
- Handles foreign keys and referential integrity in databases which do not support it (MongoDB).
- It runs in the browser, with IndexedDB support.

**Comment by coderofsalvation** [comment]
allright thx.
Have been going thru the docs.
It seems loopback really tries to solve a typical scenario, and provide tools around it.
Whereas fortune is more abstract, it doesn't really focus on particular in- or output formats by introducing intermediate formats (the adapter/serializers/transformers).
I'll give this a try.

**Comment by coderofsalvation** [comment]
one last comment:

It seems impossible for me to find anything in the documentation about *which* endpoints are created eventually.
Same goes for the jsonapi serializer.
Is there any list available somewhere? 
In the first commit of fortune, it seems there was in the README.md

**Comment by 0x8890** [comment]
It's just `/:type/:id` and all of the HTTP verbs (except for PUT, POST is preferred for creating and PATCH for updating).

**Comment by coderofsalvation** [comment]
> (it isn't ever needed).

hm I have to admit that I'm still thinking in 'endpoints', and have trouble thinking in adaptors/transformers/serializers.
Last question: how and where would you implement:

* authentication (transformer?)
* userpermissions to prevent certain users to access certain fields, operations (transformer?)
* 3rd party auth (for example passport) (transformer and ad hoc endpoints?)

**Comment by 0x8890** [comment]
For anything that requires business logic, there's the transform function. By the way, transform functions give you an elegant way to handle errors:

```js
const errors = fortune.errors

store.transformOutput(type, (context, record) => {
  if (context.request.meta['Authorization'] !== 'secret')
    throw new errors.UnauthorizedError('Not allowed to view this resource.')
})
```

Fortune.js exports its own typed errors, so that they can be re-used in application code. Notice that it's not about setting the status code to 401 but the semantics of the error type (unauthorized maps to 401), this de-couples application logic from HTTP. Throwing an error will invalidate the entire request, so a request either completely succeeds or completely fails.

I'm not familiar with passport, but if it makes necessary an ad hoc endpoint for auth, then I guess there's no choice.

**Comment by coderofsalvation** [comment]
thx for your reply.

So basically : 

* Database / Datalayer = Adapter?
* Logic/ Business layer = Transformers?
* Output/Presentationlayer = Serializers?

Are transformers bidirectional (in- and output?)

<img src="http://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgRm9ydHVuZSBmbG93CgpyZXF1ZXN0LT5TZXJpYWxpemVyOiBodHRwL2V0YyAAFwcKABMKLT5UcmFuc2Zvcm1lcnM6IHQABgggaWYgbmVlZGVkCgAWDC0-QWRhcHRlcjogY3JlYXRlL3VwZGF0ZS9kZWxldGUvZXRjCgAbBy0-RGF0YWJhc2U6IGRiIHNwZWNpZmljIG9wZXJhdGlvbgoAGAgASwoAMgoAgQkOQT8ATAoAgU4MQj8AgT8NAIF3BzoKCg&s=napkin"/>

click [here](http://www.websequencediagrams.com/?lz=dGl0bGUgRm9ydHVuZSBmbG93CgpyZXF1ZXN0LT5TZXJpYWxpemVyOiBodHRwL2V0YyAAFwcKABMKLT5UcmFuc2Zvcm1lcnM6IHQABgggaWYgbmVlZGVkCgAWDC0-QWRhcHRlcjogY3JlYXRlL3VwZGF0ZS9kZWxldGUvZXRjCgAbBy0-RGF0YWJhc2U6IGRiIHNwZWNpZmljIG9wZXJhdGlvbgoAGAgASwoAMgoAgQkOQT8ATAoAgU4MQj8AgT8NAIF3BzoKCg&s=napkin) to edit

**Comment by 0x8890** [comment]
Nice, I thought of making a diagram to make this clear. 

Yes, transform is for input and output, they are clearly labelled `transformInput` and `transformOutput`, though you may use `transform` to define both.

**Comment by coderofsalvation** [comment]
alright.
I was just reading this: https://www.thoughtworks.com/insights/blog/monoliths-are-bad-design-and-you-know-it

Fortunejs seems to focus on _decoupling_ and is _polylithic_, something the microservices-movement is focusing on these days.

Whereas do-it-all frameworks like loopback, meteor,cleverstack are more coupled/monolithic in nature.
After some experiments with the latter, I came to the conclusion that they all use pretty heavyweight  cli-tools (to get started). Some of them even did not run out of the box.
I have to admit they look impressive and some even as a designers dream, but sometimes that can turn into a developer nightmare eventually :)

I'll look more into fortunejs when I have more time.

**Comment by coderofsalvation** [comment]
Alright, i recently fell in love with fortunejs, and decided start __flowee__ (very beta!) :

http://flowee.isvery.ninja

Basically its fortunejs with some extra sauce on top, lets call it different fortunejs flavor :)
The Fortunejs datalayer & JSONAPI-serializer make a great combi to start my own 'loopback framework', but more lightweight.
Basically I added things to my likings:

* a router: since I'm coming from a express/restify background
* a middleware use() function: same reason 
* a SWAGGER-ish configuration file, where I also have put the fortunejs definitions 

These things ofcourse are based on personal taste.
I hope it'll drive more people to fortunejs.
I hope they'll also, like me, realize that fortunejs is not yet-another-bloated api-framework, but a very useful fundament for any webapplication.

**Comment by 0x8890** [comment]
nice, it's cool to see it being used in ways that I didn't expect :)
