### ISSUE TITLE
Error when trying to match on a link

### ISSUE THREAD

**Issue by Flet** [fortunejs/fortune#147]
Hello!

We're running into issues updating from 1.4.29 to any version >=1.5.0

using the default serializer, when we're trying to match on a link (`GET user?match[company]=300`) we're getting this error:
`TypeError: Cannot read property 'equal' of undefined`

It looks to be a problem around this line:
https://github.com/fortunejs/fortune/blob/master/lib/adapter/adapters/common.js#L98

There is no `type` defined because its a `link`, and attempting to add `type` to `company` throws:
`Error: Can not define both "type" and "link" on "company".`

Here are our type definitions:

user:
```js
{
  // "name" field is calculated in transform-output.js
  firstName: {type: String},
  lastName: {type: String},
  email: {type: String},
  company: {type: String, link: 'company', inverse: 'users', isArray: false},
  approved: {type: Boolean}
}
```

company:
```js
{
  name: {type: String},
  users: {link: 'user', inverse: 'company', isArray: true}
}
```

Any thoughts on this?

**Comment by 0x8890** [comment]
Whoops, it's my mistake, should check if `type` exists before trying to access a property on it. Fixed in commit https://github.com/fortunejs/fortune/commit/478a665bb0c45e08bd38f91f16221c420b60398c
