### ISSUE TITLE
Restify integration

### ISSUE THREAD

**Issue by coderofsalvation** [fortunejs/fortune#148]
I had good experiences with Restify in the past, and it also has a supersweet ip-based ratelimiter.
I was wondering if I could combine fortunejs with restify so I came up with a similar solution like this, but it didnt work:

https://github.com/fortunejs/fortune/issues/128

There might be a conflict with configuring the headers, especially the content-type.
No idea whether this is a fortune-jsonapi, fortune or restify issue , but here goes:

    var entity, entityname, fortune, http, i, jsonapi, len, model, nedb, ref, ref1, restify, serializer, store;
    fortune = require('fortune');
    jsonapi = require('fortune-json-api');    
    restify = require('restify');
  
    /*
     * setup store (serializers and adapter)
     */  
    store = fortune()
    .defineType('user', {
        name: { type: String },
     
        // Following and followers are inversely related (many-to-many). 
        following: { link: 'user', inverse: 'followers', isArray: true },
        followers: { link: 'user', inverse: 'following', isArray: true },
     
        // Many-to-one relationship of user posts to post author. 
        posts: { link: 'post', inverse: 'author', isArray: true }
    })
 
    .defineType('post', {
      message: { type: String },
 
      // One-to-many relationship of post author to user posts. 
        author: { link: 'user', inverse: 'posts' }
    })
    
    store.connect().then(function() {
      var port, server;
      server = restify.createServer({})
      server.use(fortune.net.http(store));
      server.use(restify.acceptParser(server.acceptable));
      server.use(restify.queryParser());
      server.use(restify.bodyParser());
      port = process.env.PORT || 1337;
      console.log("starting fortune @ localhost:" + port);
      return server.listen(port, function() {
        return console.log('%s %s up and running', server.name, server.url);
      });
    });

get it running:

    npm install fortune fortune-json-api restify
    node server.js

then

$ curl -X POST -H 'Content-Type: application/vnd.api+json' "http://localhost:1337/user" --data '{"name":"foo"}'
{"code":"ResourceNotFound","message":"/user does not exist"}

# Should I bother at all?

I noticed an http-extension like this (https://www.npmjs.com/package/http-router) reproduces  restify/express-style routing as well, and I got it working immediately.

    store.connect().then(function() {
      var fortunehandler = fortune.net.http(store);
      var server = http.createServer(function(req, res) {
        if (!routes.route(req, res)) {
          return fortunehandler(req, res);
        }
      });
      return server.listen(1337);

The question then would be: is it safe to say that most express/restify npm middleware modules (like this: https://www.npmjs.com/package/ratelimit-middleware) will work after a bit of DIY plumbing like above?

**Comment by 0x8890** [comment]
You might notice that Restify follows this signature for middleware, same as Connect and Express: `(req, res, next)`. The `http` wrapper from Fortune.js does not, so you will have to wrap it again to get a middleware out of it:

```js
const listener = fortune.net.http(store, { endResponse: false })

function middleware (req, res, next) {
  return listener(req, res).then(response => {
    // save the response somewhere, then call next
    next()
  })
  .catch(next)
}
```

Not sure if that is the problem, though, I've never used Restify.

**Comment by coderofsalvation** [comment]
Thx, that will do yes :)
Actually, the more I compare restify/express with the http-module, the more I'm realising that restify/express isn't a rocketscience project.
Its just a decorated http module.

I think Im just going to copy the `use()` function from restify/express, so I can easily add their middleware npm modules next to fortune middleware.
That would definately keep things lightweight.

Again, Thx!
