### ISSUE TITLE
Common adapter: limit not respected when offset is missing or zero

### ISSUE THREAD

**Issue by Flet** [fortunejs/fortune#150]
Hello!

Its great to see this project progressing! (+1)

We're seeing a but in 1.7.1 when passing `?limit=10`. We're getting all records returned instead of the limited number.

Passing `?limit=10&offset=0`: we still get all of the records.
Passing `?limit=10&offset=1`: we properly get only 10 records back.

We believe the issue has to do with this recent code change in `lib/adapter/adapters/common.js`
https://github.com/fortunejs/fortune/commit/62ccdb7f182a0a30071a652da8bd39e68c278393#diff-3c2f865c9e807f512a03b0a63a3c5119R87
```diff

options.offset && options.limit ?
-      options.offset + options.limit : options.limit)
+      options.offset + options.limit : records.length)
```

`offset` evaluates to `false` when its zero, but `true` when its greater than zero.

**Comment by 0x8890** [comment]
Whoops, logic fail.

**Comment by 0x8890** [comment]
This should be fixed in commit https://github.com/fortunejs/fortune/commit/4315439427f627410e34f530e407e9b713800c30. Let me know if it's still a problem.
