### ISSUE TITLE
How to deny requests without hit Adapter?

### ISSUE THREAD

**Issue by mctep** [fortunejs/fortune#152]
As far as I understand `transformInput` is not called on `find` method.

I have roles in my application. I need to deny access to some `types` and resources.

I can filter secret information for some user roles in `transformOutput`, but it calls `Adapter` for unnecessary fetching data from DB. 

I can deny access in `Serializer.processRequest`, but `type access` is `type` specific logic. 

I looked through code and did not find any simple decision my problem.

Is it possible to deny request before calling `Adapter`?  For example on `context` building or something else. May be it should be something like `Fortune.transformContext(type, fn);`?

**Comment by 0x8890** [comment]
Probably the easiest way to do it is simply outside of Fortune. This library by no means tries to do everything, only common things. For example, you could block a request before it even gets to Fortune's HTTP listener function.

**Comment by mctep** [comment]
Ok. Thank you! I think you are right.

May be it should be a lib for extending `Serializers`? Something like this:

```js
import extend, { createScope } from 'fortune-serializer-middleware';

class YourFirstSerilizer {}
class YourSecondSerilizer {}

const serializerScope = createScope();

const FirstSerializer = extend(YourFirstSerilizer, { scope: serializerScope });
const SecondSerializer = extend(YourSecondSerilizer, { scope: serializerScope });

const store = fortune({
    serializers: [{
        type: FirstSerializer
    }, {
        type: SecondSerializer
    }]
});

serializerScope.processRequest('secret-type', (context) {
    if (context.role !== 'admin') {
        throw new ForbiddenError('Access denied to secret type');
    }

    // also we can set some default options
    context.options.include.push('field');

    return context;
});
```

What you think about this? I can try to write it :-)

**Comment by 0x8890** [comment]
If you're using ES6 class it's not necessary. Just use `super`:

```
class MySerializer extends JSONSerializer {
  processRequest (context) {
    // do some auth checking here, then call super
    return super.processRequest(...arguments)
  }
}
```

**Comment by mctep** [comment]
Yep, but if I use few serializers I need do it in each.

This is only:
* simple way to do it;
* share context transformers (`middleware`) between serializers;
* transform context on specific resource type.

**Comment by mctep** [comment]
I write some [helper](https://gist.github.com/mctep/809069e182bbf0f5fbf1) on gist. There is my case for using `proccesRequest` for json api and unit test it.

I don't really like this decision, but it will may be useful somebody for simple redefine `Serializer` behavior.

**Comment by 0x8890** [comment]
I'm not sure if I understand your intent but it seems that you want to run some functions after `processRequest`. It could be simpler without over-engineering it:

```js
/**
 * Wrap a serializer class to run functions after `processRequest`. This
 * returns a new class.
 *
 * @param {Function} class
 * @param {Function[]} fns - An array of functions to be executed serially.
 * @return {Function}
 */
function postProcessRequest (Serializer, fns) {
  return class WrappedSerializer extends Serializer {
    processRequest () {
      return fns.reduce((chain, fn) => chain.then(fn),
        Promise.resolve(super.processRequest(...arguments)))
    }
  }
}
```

**Comment by mctep** [comment]
Wait... Oh f...! :laughing: You are right!

But I want to have elegant way to define this functions for access control level in **`type` scope**.
I will think further how to make it in the most optimal way.

Now I figure out few ways:

1. The simplest way is realize ACL in `transformOutput`, but it affects DB. And it is strange, that the access is denied, but the record has been read.
2. Make it before `Serializer` initialize `context`. It is not the solution, because it is no `type` scope.
3. Make it in `proccessRequest`. As I understand in this way I should check direct `request` to `type` and `linked` request with `include` option.

**Comment by mctep** [comment]
I want to say `type`: "Hey, `Record Type`! Before you make some action, please, check some context meta". And do not think about serialize process and requests.

**Comment by 0x8890** [comment]
Regarding the first option, sometimes it is actually necessary to read the record to determine if access should be granted or not. This is not always the case and it may be more efficient to block the request before it gets to that point, which is what I guess you're trying to do. 

With a little modification of the above code, I think this is what you're going for:

```
/**
 * Wrap a serializer class to run a function after `processRequest` based on the record type.
 * This returns a new class.
 *
 * @param {Function} Serializer
 * @param {Object} hash - Keyed by type name, valued by function.
 * @return {Function}
 */
function postProcessRequest (Serializer, hash) {
  return class WrappedSerializer extends Serializer {
    processRequest () {
      return Promise.resolve(super.processRequest(...arguments))
      .then(context => {
        const type = context.request.type
        return type in hash ? hash[type](context) : context
      })
    }
  }
}
```

**Comment by mctep** [comment]
Yes, it is.

OK. Let me to summarize how to realize access control.

* For `create`, `update`, `delete` methods it should be using context from `transformInput`;
* For direct `find` (`store.request({ method: 'find', type: 'target' })`) method to resource use `postProcessRequest` with `type` hash;
* For including record by reference `store.request({ method: 'find', type: 'parent', include: ['link'] })`...

The first and second done. It is cool. The last option. Real example:

```js
// some online shop
defineType('price', { amount, currency });
defineType('item', {
  restockPrice: { link: 'price' },
  sellingPrice: { link: 'price' }
});
```

Admin has access to both prices in item, User has access only to `sellingPrice`. So business logic is:

```js
// it also added by postProcessRequest
checkReadAccessForReference('item', 'restockPrice', (context) => {
  const { include, meta } = context.request;
  if (meta.role === 'user') {
    context.request.include = without(include, 'restockPrice');
  }
});
```

**Comment by 0x8890** [comment]
Hmm, to be honest I think you should try to contain the business logic in transform functions, including access control. Consider if access is granted on a per record basis according to the specific user, then there's no choice but to fetch the record first to determine if the application should grant access or not. Your current approach won't work as soon as access control becomes more granular.

**Comment by mctep** [comment]
OK. Probable hit `Adapter` before denying request is not really big problem like it looks on the first side.

Thank you for your patience and detailed answers. :beers: 

`Fortune` is the best ever tool to make big things happens! :+1:

**Comment by mctep** [comment]
By the way I stopped for myself on next general flow:
```js
function defineType(store) {
  store.defineType(name, type);

  // define should the request to proccess
  store.processRequest(name, accessRequest);
  // define should the resource be changed, created or deleted
  store.transfomInput(name, accessInput);
  // define what we do with the resource
  store.transfomInput(name, transfomInput);
  // define what we show in the resource in a general case
  store.transfomOutput(name, transformOutput);
  // define what we show in the resource
  // when we reference to it from other resource
  store.transfomOutput(name, accessOutput);  
}
```
