### ISSUE TITLE
Authentication and password hashing approaches

### ISSUE THREAD

**Issue by maximusmusterus1** [fortunejs/fortune#154]
Hi there,

I want to use fortune.js to provide an API for an application. I really like this library since it allows me to build simple CRUD APIs efficiently, which represent 90 percent of the logic of my application.

But with authentication things got a little tricky for me, so I would love to hear any opinions and suggestions from people who are more experienced with fortune.js.

So what I planned to do is to use fortune.js in conjunction with koa and write a separate middleware for token based authentication and rights management. This middleware gets injected before fortune.js so in case the user has insufficient rights or is not authenticated a error status will be send. Otherwise it will continue to let fortune.js do it's thing. Is this a reasonable approach to handle this problem? Or what would be the right place to handle JWT-based user authentication for a fortune.js-based API?

I experimented with this for a bit, but I came to a little problem. I will store users via fortune.js. Lets say (for simplicity) a user has a name and an password hash. I don't want the password hash to be exposed via the API. I could use a output transformation and delete the hash from the record but this way, I also can't access this property via Fortune.request. But I need to access it, in order to check user logins in my authentication middleware. Is there a clean way to solve this issue so the hash is not exposed via API but accessible internally? (Yeah I could skip fortune.js altogether and access the database directly but that would kill the abstraction somehow.

Thanks!
Yours,
Max

**Comment by 0x8890** [comment]
No problem, if you need internal access, just store properties on the `context` object. So if you have a `hash` property on a record you could do something like:

```js
function transformOutput (context, record) {
  if (!('hash' in context.response)) context.response.hash = []
  context.response.hash.push(record.hash)
  delete record.hash
  return record
}
```

Fortune.js itself does this internally when passing data through the request method.

I hope that answers your question.

**Comment by maximusmusterus1** [comment]
Thanks a lot! Exactly what I needed.
