### ISSUE TITLE
Callback support

### ISSUE THREAD

**Issue by IonicaBizau** [fortunejs/fortune#158]
I know we can *unpromisify* the things, but is it possible to have this natively?

```js
var f = fortune();
f.connect(function (err, data) {
   /* do something after connect */
});
```

Or:

```js
f.adapter.create("foo", [{...}], function (err, data) {
  /* do something after insert */
});
```

**Comment by 0x8890** [comment]
Hmm, what would be the motivation for this? The Promise implementation may already be customized, and Bluebird is plenty fast. It would just be a burden for anyone writing their own classes to support both promises and callbacks, so I'd rather have one or the other.

**Comment by IonicaBizau** [comment]
I'm not a fan of bluebird because it's pretty big (244K). What about using the ES6 native `Promise`s?
I will most probably create my high-level wrapper which will use fortune so, using promises it's not really a big issue, but using bluebird could be because it's big.

Is there any specific reason to use bluebird instead of ES6 promises?

Thanks! :joy: :cake:

**Comment by 0x8890** [comment]
Bluebird is actually faster than all current ES6 Promise implementations, this is because they are not implemented in C++ but JS internally, and the major vendors don't do it very efficiently. Size is not a concern for Node.js, but the browser build it doesn't come with any Promise implementation.

**Comment by IonicaBizau** [comment]
Ah, I see! Then I'm closing this for now. :+1:
