### ISSUE TITLE
Success response when creating resource with a relationship with multiple data member

### ISSUE THREAD

**Issue by mak1986** [fortunejs/fortune#172]
This is the request:
```javascript
{
    "data": {
        "type":"user",
        "attributes": {
            "name": "John Doe"
        },
        "relationships":{
            "groups":{
                "data":[
                    {"type": "group", "id" : "1"},
                    {"type": "group", "id" : "2"}
                ]
            }
        }
    }
}
```

The request was accepted and the resource was created with a relation to group id 1 only.

I couldn't figure out why until i read on jsonapi.org that a relationship object has only 1 data member. 

> If a relationship is provided in the relationships member of the resource object, its value MUST be a relationship object with a data member. The value of this key represents the linkage the new resource is to have.

Should the response not throw an error instead?

**Comment by 0x8890** [comment]
Perhaps this is an issue for [fortune-json-api](https://github.com/fortunejs/fortune-json-api)?

Also what does your type definition look like? There is a test for this scenario https://github.com/fortunejs/fortune-json-api/blob/122accc7fe99e013eec8e9c7bee9f8dc61dd6241/test/index.js#L141-L146 and it seems to work fine. does your `groups` field have the `isArray` attribute?

**Comment by mak1986** [comment]
Yep forgot to add isArray attribute. :)
