### ISSUE TITLE
Add documentation on clustering

### ISSUE THREAD

**Issue by 0x8890** [fortunejs/fortune#174]
With WebSocket, things get complicated, since it holds stateful connections. One can scale a stateful server by:

- Using inter-process communication (IPC)
- Using an external data store.

IPC would be necessary to scale past a single thread, so I'll focus mainly on that. There is still the limitation of available memory on a single machine though.

**Comment by thibremy** [comment]
I agree with you, personally I use [kue](https://github.com/Automattic/kue) mixed with fortune to scale my API more "easily".

Used with a tiny [gateway pattern](http://microservices.io/patterns/apigateway.html) we can keep clean "isolation".

**Comment by 0x8890** [comment]
Added some notes https://github.com/fortunejs/fortune/commit/734ca5f7e18b02d55fa95e5ab68d9cf0d467a9fb.
