### ISSUE TITLE
Express and Fortune

### ISSUE THREAD

**Issue by ksnyde** [fortunejs/fortune#178]
I'm new to Express _and_ Fortune and so I'm still trying to figure out how to connect the two appropriately. I had thought maybe I could do the following:

    app.use(compression());
    app.use(helmet());
    app.listen(3000, function() {
      debug('listening on port 3000');
      debug(`Environment set to "${ENV}"`);
    });

    const routerSetup = function() {

      app.get('/ping', function(req, res) {
        res.send({
          uptime: '',
          users: '',
          loadAverages: [],
          diskCapacity: []
        });

        app.get('/actions', store);
        app.get('/markers', store);

      });
    };

    store.connect().then(() => {
      debug('fortune connected to mongo');
      routerSetup();
    });

This would allow most of my endpoints to be serviced via Fortune but then to have a few that lived outside of Fortune's scope. I know this is more of a question than an issue but if there's a short answer it would save me a lot of time. Happy to turn any answer you can give into a PR for documentation purposes if that's helpful. 

BTW, the error I get is:

> new TypeError('The definition of "' + key + '" must be an object.')

_in `validate.js` line 40

**Comment by 0x8890** [comment]
You probably want to use it as a middleware. There really isn't much to it:

```js
const listener = fortune.net.http(store)

// Make sure it's the very last middleware, or set the `endResponse` option
// and handle the returned Promise to use it as a real middleware.
app.use(listener)
```

P.S. the error that you got may be related to a breaking change in a major version. I noticed the error message was wrong but haven't published a patch version for it yet.

**Comment by ksnyde** [comment]
Ok thanks. Would it be helpful for me to send a PR with an update to the README? Happy to do that if it helps. Also could see that you might not get much out of that but let me know.

**Comment by 0x8890** [comment]
I was thinking of just adding an examples folder, this would be trivial to add.

**Comment by ksnyde** [comment]
Makes sense. Love the work so far, inspiring.

**Comment by ksnyde** [comment]
On a side note, I am still running into that same error ... but I think it must be to related to breaking changes in the API as I am referencing a spike I did a month ago. Am I right to say that you've changed the `adapter` API to allow multiple adaptors? I also looks as though the individual definition is no longer a hash but a tuplet [adapter, optionHash].

**Comment by 0x8890** [comment]
Yup, I changed how the configuration works to avoid naming things. The old adapter config looked like this:

```js
{ adapter: { type, options } }
```

This is now simplified so that it does not rely on the names of the keys:

```js
{ adapter: [ type, options ] }
```

**Comment by ksnyde** [comment]
Oh, you also got rid of `defineType` and require all type definition in the constructor. What was the thinking behind that?

**Comment by ksnyde** [comment]
actually nevermind, I think I like the new approach better and I don't want to waste your time

**Comment by 0x8890** [comment]
Yes, there had to be some breaking changes, but at the end it's as simple as it can possible be. Before there were methods that needed to be called (`defineType`, `transformInput`, `transformOutput`) which were kind of pointless because they only needed to be set up once and in no particular order. Even `connect` is now optional. So you can set up an instance with only the constructor and immediately use the `request` method.
