### ISSUE TITLE
link to different database

### ISSUE THREAD

**Issue by ksnyde** [fortunejs/fortune#179]
I have my data partitioned into the following databases: reference, transactional, and user. In each case I have a separate express router configuring the models for each;  while that concern is somewhat external to fortune I'm wondering if there is a way to indicate a linked relationship between backend stores. Having them semantically linked is important to me yet the logical separation is providing me the ability to apply varying scaling strategies to the various types of data. 

As an example ... let's say I have  a "comment" which has been shared on a social network. The inventory of possible social networks is reference data (`db.ref.social_networks`) but the comment -- a transactional record `db.trans.comment` -- needs to link to the particular network which it was shared on. I'd like to define this something like:

    comment: {
        shared_on: { link: 'ref.social_networks', isArray: true }
    }

Is this possible today?

**Comment by ksnyde** [comment]
To be honest, this may come down to my newness to Mongo, but an assumption I've made is that a client connection is to a single DB at a time. this has shaped my thinking so far in terms of modularity.

**Comment by 0x8890** [comment]
MongoDB has no concept of "relationships", it's done entirely at the application-level (in this case, Fortune.js). What Fortune.js does is store links as fields on an object, and this won't scale if you really need a massive amount of links. 

In MongoDB the limit on document size is 16 MB. Postgres has a limit of 1 GB per column, and graph databases usually have a limit of a few billion relationships. Generally there are physical limitations to this approach.

What would probably be a better approach is to just use a plain old string or object field to store this data. Regarding the original question, each Fortune.js instance can only connect to one database at a time, so it wouldn't be feasible to manage relationships across databases.

**Comment by ksnyde** [comment]
Sure I understand that mongo has no relationships, and having been a Couchbase user for many years I also understand the trade offs between links and embedded records. My point about scaling was a bit different. Anyway, my hope was to keep the references map, all the way to the front end (which are EmberJS SPA's using ember data). I can use fortune unaware references but then I lose all the JSON-API goodness the serializer is providing me. Seems like the physical topology should be able to be abstracted away from but maybe that's my optimism speaking. 

Ken Snyder
ken@ken.net

    _____________________________
