### ISSUE TITLE
Count property doesn't get to be serialized by msgpack

### ISSUE THREAD

**Issue by kketch** [fortunejs/fortune#181]
A count property is set by fortune adapters on the "records" array, thus making requests to a local fortune instance correctly returns as expected the "records" array with the count property set to the total number of records without limit and offset as described in the API Reference: 

```javascript
instance.request(requestData).then(response => {
  const count = response.payload.records.count
  //  count can be retrieved in this case
})
```

However when making a request a remote fortune instance using `fortune.net.request` the count property is missing:

```javascript
fortune.net.request(client, {request: requestData}).then(data => {
  const count = data.response.payload.records.count
  // here count is undefined
})
```

It seems that as soon as the response is encoded by msgpack, the count property is lost as msgpack does not preserve this count property. Msgpack (& JSON serialization) don't support custom properties attached to an array. 
Is there anything to do here to get a more consistent behavior ? It this a bug ? If it is, maybe another way to store the total count of records on the response could fix this

**Comment by 0x8890** [comment]
Definitely a bug. Could be fixed by simply not putting the `count` as a property on the records array.

```
{
  payload: {
    records: [ ... ],
    count: 5,
    include: { ... }
  }
}
```

Thanks for reporting, it shouldn't be hard to fix, PR welcome.

**Comment by 0x8890** [comment]
PR has been merged.
