### ISSUE TITLE
Make useIPC opt-in only

### ISSUE THREAD

**Issue by kketch** [fortunejs/fortune#190]
Hello, the new IPC feature that allows workers to be notified of changes triggered by another worker over IPC is quite handy, but I think that the useIPC option enabling it should not default to true, but false.
It is quite unexpected that this behaviour pops up with the new 3.3.0 minor versions since the new default behaviour (useIPC = true) do not work in regular node processes, since `process.send`is not available on node processes without parent IPC channels

**Comment by 0x8890** [comment]
Are you sure? The `useIPC` option only has any effect if the process is already a worker process, so `process.send` will only ever get called from a worker process with the `useIPC` option enabled.

Maybe it is better to be safe than sorry though, I guess I'll make it `false` by default and just update the docs to reflect that.

**Comment by 0x8890** [comment]
Done in commit https://github.com/fortunejs/fortune/commit/a5bff11f71dfd7e96454090207d40be28a82aebf.

**Comment by kketch** [comment]
It would throw and complain that `process.send` is not a function in a regular node process.
Nice :)
