### ISSUE TITLE
successClass: undefined?

### ISSUE THREAD

**Issue by adnasa** [fortunejs/fortune#193]
Found that you have `successClass` called in this [file](https://github.com/fortunejs/fortune/blob/bfd9dfde529a04b0bc03028c76792b1fac6821bd/lib/common/response_classes.js#L8-L10), but where were they defined?

---

Remove?

**Comment by 0x8890** [comment]
Right here :)

https://github.com/fortunejs/fortune/blob/bfd9dfde529a04b0bc03028c76792b1fac6821bd/lib/common/response_classes.js#L33
