### ISSUE TITLE
Return null in output function?

### ISSUE THREAD

**Issue by voronianski** [fortunejs/fortune#197]
I created a token type for my application in order to save authorized session:

```js
// /src/types/token.js
import fortune from 'fortune';
import config from 'c0nfig';
import * as passwords from '../utils/passwords';

const createMethod = fortune.methods.create;
const updateMethod = fortune.methods.update;

const NotFoundError = fortune.errors.NotFoundError;
const BadRequestError = fortune.errors.BadRequestError;

const recordType = {
    name: 'token',

    collection: 'tokens',

    definition: {
        userId: {
            type: String
        },
        expireAt: {
            type: Date
        }
    },

    index: {
        keys: {
            expireAt: 1
        },
        options: {
            expireAfterSeconds: 0 // gets deleted from db as soon as expire time comes
        }
    },

    async input(context, record) {
        const method = context.request.method;

        if (method === createMethod) {
            delete record.id;

            const users = await context.transaction.find('user', null, {
                match: {
                    email: record.email
                }
            });
            if (!users.count) {
                throw new NotFoundError(`There is no user with email - ${record.email}`);
            }

            const [ user ] = users;
            const same = await passwords.compare(record.password, user.password);
            if (!same) {
                throw new BadRequestError('Passwords do not match');
            }

            record.userId = user.id;
            record.expireAt = new Date(Date.now() + config.auth.tokenTTL);
            return record;
        }

        if (method === updateMethod) {
            return record;
        }

        return null;
    },

    output(context, record) {
        // is it possible to not return values somehow for some methods?
        delete record.userId;
        return record;
    }
};

export default recordType;
```

The ideas are:

- when user logins to api he's sending `{email, password}` pair to `POST /tokens` resource
- if user exists and credentials are valid we'll create a `token` type in db with `userId` and `expireAt` fields. Response will look like:

```json
{
  "data": {
    "type": "tokens",
    "id": "853467ba874929ed7d72d8a6",
    "attributes": {
      "expire-at": "2016-04-20T20:07:45.000Z"
    },
    "links": {
      "self": "/tokens/853467ba874929ed7d72d8a6"
    }
  }
}
```

- api consumer can use token id to make to requests to `GET,POST,PATCH,DELETE /protected/endpoint?token=853467ba874929ed7d72d8a6`
- on protected endpoint request I'm searching for `token` in db. If it's not expired I will get `userId` and get necessary user data if needed

However this approach has issue - when requesting `GET /tokens` it will return all token objects from db containing their ids... 

If I try to return `null` in `output` function for `find` method I get such error:

```bash
GET /v1/tokens 500 5.435 ms - 34
TypeError: Cannot read property 'id' of null
    at JsonApiSerializer.mapRecord (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune-json-api/lib/helpers.js:183:20)
    at /Users/dmitri/github/dhhb/api-fortune/node_modules/fortune-json-api/lib/index.js:191:19
    at Array.map (native)
    at JsonApiSerializer.showResponse (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune-json-api/lib/index.js:190:46)
    at JsonApiSerializer.processResponse (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune-json-api/lib/index.js:84:30)
    at /Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/lib/net/http_server.js:249:10
    at tryCatcher (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/promise.js:684:18)
    at Async._drainQueue (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/dmitri/github/dhhb/api-fortune/node_modules/fortune/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Maybe I'm thinking in wrong direction? What would you suggest? 

I would like to stay with fortune, jsonApiSerialiazer and other goodness provided by this awesome library and not move login api to separate express endpoints. Maybe there's a way not to return data on GET requests?

**Comment by 0x8890** [comment]
You're on the right path, unintentionally. The idea here is to manually throw an error if the client is unauthorized to access a token. Instead of returning null, you would write some conditional `if` to check if the client is authorized, and if not, throw an error. Something like this:

```js
function output (context, record) {
  if (context.request.meta.headers['authorization'] !== 'secret')
    throw fortune.errors.UnauthorizedError('Not allowed to read this resource.')

  return record
}
```

An additional step is to add some middleware to intercept this request before it even reaches fortune, since you know that getting the tokens collection is not allowed.

**Comment by 0x8890** [comment]
P.S. there is a problem in your `input` function, there is a third argument, `update`, which is only used for update requests. it is expected that the `update` object is returned if it is passed in as an argument.

```js
function input (context, record, update) {
  if (context.request.method === 'create') return record
  if (update) return update
}
```

**Comment by voronianski** [comment]
@0x8890 

>  The idea here is to manually throw an error if the client is unauthorized to access a token. Instead of returning null, you would write some conditional if to check if the client is authorized, and if not, throw an error.

This means that it's ok to throw Forbidden error everytime when request `GET /tokens` (because tokenIds are actually access tokens for api consumers)

> An additional step is to add some middleware to intercept this request before it even reaches fortune, since you know that getting the tokens collection is not allowed.

I don't want to create a middleware because some of the api resources are public, another ones should have access token in request, that means that I will end up with a list of like:

```js
router.get('/token(s?)', notAllowed);
router.patch('/token(s?)/:id', notAllowed);
router.post('/article(s?)', checkAuth);
router.patch('/article(s?)/:id', checkAuth);
router.del('/article(s?)/:id', checkAuth);
// etc.

router.use(fortune);
```

> P.S. there is a problem in your input function, there is a third argument, update, which is only used for update requests. it is expected that the update object is returned if it is passed in as an argument.

Yeah, I know, but in this case I don't want to allow updating tokens, so I can throw an error or rerturn a record.

**Comment by 0x8890** [comment]
It's completely safe to throw errors in the transform functions, nothing gets persisted if an error is thrown and the error is handled gracefully.

A blacklisting middleware wouldn't be so difficult:

```js
app.use((req, res, next) => {
  const parts = req.url.split('/')
  if (parts[1] === 'tokens' && parts.length === 2) {
    res.statusCode = 404
    return res.end()
  }

  return next()
})
```

If you want to disallow updating tokens, it's better to explicitly throw the appropriate error (`fortune.errors.MethodError`).

**Comment by voronianski** [comment]
@0x8890 ok, thanks! I will show you the result when it will be ready.
