### ISSUE TITLE
Default HTML serializer

### ISSUE THREAD

**Issue by 0x8890** [fortunejs/fortune#198]
I think that having a default HTML output for humans will greatly help improve accessibility and understanding. 

The default JSON serializer is not hypermedia, while HTML is obviously a hypermedia format. In conjunction with the Micro API serializer and content negotiation, I think that an API that is accessible to both humans and machines is demonstrable.

The hypermedia formats include the context and controls, so all of the querying options will be accessible from the HTML page.

**Comment by kketch** [comment]
For what its worth I think is a great idea
