### ISSUE TITLE
Use of undeclared "handleChange" function in websocket_server.js

### ISSUE THREAD

**Issue by kketch** [fortunejs/fortune#203]
The websocket server when running in cluster mode seems to call an undeclared function :

https://github.com/fortunejs/fortune/blob/master/lib/net/websocket_server.js#L184

**Comment by 0x8890** [comment]
Oops, this seems to be a regression. Should be `change` instead of `handleChange`.

**Comment by 0x8890** [comment]
Fixed in commit https://github.com/fortunejs/fortune/commit/3d71a4977d82bfa6913671100afe20d48f033982.
