### ISSUE TITLE
Question: best way to handle ad-hoc endpoints?

### ISSUE THREAD

**Issue by paul42** [fortunejs/fortune#206]
I was wondering if there is an easy 'insertion' point to handle non-db related requests - or if I should just slot fortune into another framework (if so, do you have any examples that are good fits?)

for example:
I want a POST to /newPayment with a body to end up making a call to paypal, and returning an object that is a combination of the original post to /newPayment & the response from paypal - 

is this best handled by just making a /payment 'type' and having the business logic sit in the 'inputTransform' ? 

Thanks!

**Comment by 0x8890** [comment]
>is this best handled by just making a /payment 'type' and having the business logic sit in the 'inputTransform' ?

Yes, you just answered your own question. The transform functions exist to implement any sort of business logic.

**Comment by paul42** [comment]
thanks for responding - I appreciate the quick response! would an example help the documentation, or is there any way I can contribute?

**Comment by 0x8890** [comment]
I think the documentation about transform functions is fine, it's meant to be very open-ended. 

There aren't many things I can think of as improvements at the moment, mostly I think more examples are missing.

**Comment by paul42** [comment]
Thanks for clarifying!

**Comment by paul42** [comment]
Thanks for clarifying
