### ISSUE TITLE
Question: Best way to insert logging?

### ISSUE THREAD

**Issue by paul42** [fortunejs/fortune#207]
Sorry for the spam, but I was wondering if you have any suggestions for the easiest way to insert logging? I'm a fan of the [bunyan](https://github.com/trentm/node-bunyan) library - and I was wondering if it's possible to extend the method of [request](http://fortunejs.com/api/#fortune-request) with logic for logging, the way that [plugins extend adapters](https://github.com/fortunejs/fortune-mongodb/blob/master/lib/index.js#L20) would I just put them in the same serializers: [] array, (as an http serializer?) and just have them call 'super' or something like you mention in this [older issue](https://github.com/fortunejs/fortune/issues/152)

I have more enthusiasm than experience, so I appreciate your help, and your great project!

**Comment by paul42** [comment]
namely, from that last issue, where would I put this code that you mention:
    /**
     * Wrap a serializer class to run a function after `processRequest` based
     * on the record type. This returns a new class.
     *
     * @param {Function} Serializer
     * @param {Object} hash - Keyed by type name, valued by function.
     * @return {Function}
     */
    function postProcessRequest (Serializer, hash) {
      return class WrappedSerializer extends Serializer {
        processRequest () {
          return Promise.resolve(super.processRequest(...arguments))
          .then(context => {
            const type = context.request.type
            return type in hash ? hash[type](context) : context
          })
        }
      }
    }

**Comment by thibremy** [comment]
Just implement a basic middleware layer with bunyan with your favorite framework (express, koa, connect ...).

If you want to log response  "after" fortune, take a look at [Fortune.net.http](http://fortunejs.com/api/#fortune.net-http). You can switch ` endResponse` to false.

**Comment by 0x8890** [comment]
@paul42 regarding that code snippet, you would use it like this:

```js
fortune.net.http(instance, {
  serializers: [
    // Replace JsonSerializer with any one that you want.
    postProcessRequest(fortune.net.JsonSerializer, [
      contextRequest => {
        // Here you can log anything regarding the request.
        return contextRequest
      }
    ])
  ]
})
```

**Comment by paul42** [comment]
ah, I think I get it, I'll go ahead and try this method and report back. I'll close this for now since you've answered my question.

Thanks again!
