### ISSUE TITLE
Multiple Adaptors

### ISSUE THREAD

**Issue by BarryThePenguin** [fortunejs/fortune#208]
Is there a way to use different adaptors for different types?

I looked at creating seperate instances of two stores and connecting both of them to my app server, but only the first one is available.

My other thought was creating a custom adaptor, that switched underlying adapters based on the type being requesting.

Are there any suggested approaches to this? I'm really enjoying using this with ember-data, thanks!

**Comment by 0x8890** [comment]
There are no plans to support multiple adapters per instance. The main reason is that for transactions to work, it must use the same adapter.

If you insist on multiple adapters, then probably you will need an adapter to route requests based on the type. If you don't care about transactions then it should be fine.

**Comment by BarryThePenguin** [comment]
Good to know. 

I already have a custom adapter. So I'm looking to use that along side a database adapter (probably nedb). I'll look into another custom adapter to route the two based on type.

Thanks for your quick reply
