### ISSUE TITLE
How can i deploy fortune not at root path?

### ISSUE THREAD

**Issue by datouxia** [fortunejs/fortune#216]
I want installed fortune at http://project.exmaple.com/api. but I find the link in the types are wrong.
try to modify http_html_serializer.js:51
var prefix = this.options.prefix || ''  to var prefix = this.options.prefix || '/api'
The link in the html are right, but the port from postman not working.
Thanks for giving any help!

**Comment by 0x8890** [comment]
Good find. This is a bug related to this file: https://github.com/fortunejs/fortune/blob/master/lib/net/http_initialize_context.js

The prefix needs to be removed from the url before trying to parse it internally.

**Comment by 0x8890** [comment]
Done https://github.com/fortunejs/fortune/commit/05ddfb90debd89a8a89712024a9ff186e149c2a3.
