### ISSUE TITLE
internal request for resource, not by ID

### ISSUE THREAD

**Issue by bendman** [fortunejs/fortune#218]
Is it possible to request a resource interally, but not by ID.  For example, I'm using fortune with the postgres adapter and json-api serializer, and I want to make an internal request for a person by name.

I've checked the docs of the adapter, serializer, and fortune itself, but I can't find any example or documentation of how to search for a resource using a non-ID field.

**Comment by 0x8890** [comment]
Of course:

```js
store.adapter.find(type, null, {
  match: { name }
})
```

I will note this as a fault in the documentation.

**Comment by bendman** [comment]
Ah, thank you.  Are the `find` options documented anywhere?

Also, this is working, but the following part of the docs seems to be wrong as well:

> The response object may contain the following keys:
> - meta: Meta-info of the response.
> - payload: An object containing the following keys:
>   - records: An array of records returned.
>   - count: Total number of records without options applied (only for responses to the find method).
>   - include: An object keyed by type, valued by arrays of included records.

There is no response object with those keys.  The response I get is just a single array with a `count` property added on (with the same value as `.length`)

**Comment by 0x8890** [comment]
Nah that is correct: you're looking at the doc for `Fortune.request` which is different from `Adapter.find`.

**Comment by 0x8890** [comment]
Documentation has been updated https://github.com/fortunejs/fortune/commit/9067e9704dd30fec4914e1a3b46b69647321e05d.
