### ISSUE TITLE
Lazy-loading "links"

### ISSUE THREAD

**Issue by mfenniak** [fortunejs/fortune#219]
When a record type has a link with lots of objects, it can sometimes be expensive to load all of the object ids in the adapter and send them through the API.  Is there currently any way to address this in fortunejs?

For example, I have a 'parent' record type and a 'child' record type.  The parent record has a link to the child with isArray:true.  If each parent object has 10,000 child links, it appears that when loading ```/parent```, the adapter has to populate the relationship ```child``` with all 10,000 ids of the child objects.

Ideally what I would like, as a user of the JSON-API serializer, is for my parent's child relationship to contain the links to load the child, but not the data referring to the individual child objects themselves.  My thought right now is that I could introduce a custom serializer to apply this change on expensive relationships, but I wanted to see if there were any grander thoughts on how this should work in fortunejs.

**Comment by 0x8890** [comment]
Yeah, it's quite simple:

```js
store.request({
  type, ids, options: { fields: { fieldWithLotsOfLinks: false } }
})
```

To get a serializer to always do this, you'd need to subclass it and extend the `processRequest` method. Something like:

```.js
const fortune = require('fortune')
const HttpSerializer = fortune.net.http.Serializer

class CustomSerializer extends JsonApiSerializer(HttpSerializer) {
  processRequest () {
    return super(...arguments)
    .then(context => {
      // Add some custom application logic automatically.
      if (context.request.type === someType)
        context.request.options.fields.fieldWithLotsOfLinks = false

      return context
    })
  }
}
```

**Comment by mfenniak** [comment]
Thanks for the super-quick response.  That was very clear and addresses instructing the adapter to not load a specific relationship.  The CustomSerializer required a bit of tweaking, so I threw the tweaked version into a gist for posterity's sake (https://gist.github.com/mfenniak/c23bd1c1dd5fdd7f2eb3470c13cf359a).

The result here is that the field is completely omitted in the JSON-API response, which I can probably work with.  Ideally though, I'd like to be able to provide the links to load the relationship back to the API client.  In other words, .relationships.[...].links is still serialized, but .relationships.[...].data is not present.

For example, this is the JSON-API response without disabling the field:

```js
{
  "type": "users",
  "id": "1465308112610-eebe1dce",
  "attributes": { ... snip ... }
  "relationships": {
    "group": {
      "links": {
        "self": "/users/1465308112610-eebe1dce/relationships/group",
        "related": "/users/1465308112610-eebe1dce/group"
      },
      "data": []
    }
  },
  "links": {
    "self": "/users/1465308112610-eebe1dce"
  }
}
```


, this is the JSON-API response when applying your response to disable the field:

```js
{
  "type": "users",
  "id": "1465308112610-eebe1dce",
  "attributes": { ... snip ... }
  "links": {
    "self": "/users/1465308112610-eebe1dce"
  }
}
```

, and this is the response I'd *like* to see; .relationships.group.links is present, but .relationships.group.data is not:

```js
{
  "type": "users",
  "id": "1465308112610-eebe1dce",
  "attributes": { ... snip ... }
  "relationships": {
    "group": {
      "links": {
        "self": "/users/1465308112610-eebe1dce/relationships/group",
        "related": "/users/1465308112610-eebe1dce/group"
      }
    }
  },
  "links": {
    "self": "/users/1465308112610-eebe1dce"
  }
}
```

It seems like this is still compliant with the JSON-API spec, which requires only that a ""relationship object" MUST contain at least one of... links, data, meta".  Any thoughts on how to accomplish that?  Or, for that matter, whether it's a good idea?  It seems like this would require a change to fortune-json-api's mapRecord function, which isn't in a position to be overridden.

**Comment by 0x8890** [comment]
That is unintentional, the JSON API serializer should always show links whether the `fields` options was used or not. Can you raise an issue over there?
