### ISSUE TITLE
How to implement last of field defined as isArray: true

### ISSUE THREAD

**Issue by xcapt** [fortunejs/fortune#220]
Hi, 1st:  great piece of work on fortunejs.

Not sure how to handle this:
i have changes defined as a field (isArray true) in a record type and would like to implement a lastChange field returning only the last one, what is the recommended way to do this:
1) Transform function ?
2) field with Function record type ? it is listed in the API doc but cannot find an example

Thanks in advance

**Comment by 0x8890** [comment]
A transform function would work here:

```js
[ input, function output (context, record) {
  record.lastChange = record.changes[record.changes.length - 1]
  delete record.changes
  return record
} ]
```

There are tests that show how to use custom types: https://github.com/fortunejs/fortune/blob/a4260d8ee90aba3589b8b727f1043a62be2c8bd2/test/integration/adapters/memory.js#L62-L84

However, custom types are only implemented for the memory adapter so far, and mostly they serve as input validation, so it's not what you want.

**Comment by xcapt** [comment]
excellent thanks.

if I may 2 further question:
- is there a way to make this new field added by transform appear in the default html rendering
- is transforms also the place to de-reference this field ? how would i go about having the found change object directly in lastChange ?

Thanks

**Comment by 0x8890** [comment]
1) Yes, you would have to add the new field into the record type definition. The reasoning is that the table headers are shown based on record type definitions, and type coercion to a string is done by reading the definition.
2) Yes, you could also de-reference it there.

**Comment by xcapt** [comment]
Sorry for the additional questions, i really like the potential of your solution :

1) ok, I have added, lastChange: { link: 'change' }, yet in the /item/id/lastChange does not seem to use the id properly, the page list cahnge fields but no data. any clue ?

2) is there any code sample of dereferencing in the code repo ?

**Comment by 0x8890** [comment]
hmm, I would have to see your example to figure it out. 

dereferencing should be as simple as:

```js
function output (context, record) {
  return store.adapter.find(type, [ record.lastChange ])
  .then(records => {
    record.lastChange = records[0]
    return record
  })
}
```

**Comment by xcapt** [comment]
If possible, an example of the 2 in the code and doc would really help.
 And I think I would interested to see how it looks in the default renderer as well, as it is so great to explore data without having to build a dedicated UI.

**Comment by 0x8890** [comment]
Here's an example using the test data. You can run it yourself by pasting it into any project that requires fortune.

```js
const http = require('http')
const instance = require('fortune/test/integration/test_instance')
const fortune = require('fortune')

instance()
.then(store => {
  store.recordTypes.user.lastFriend = { type: Object }

  const userOutput = store.transforms.user[1]

  store.transforms.user[1] = function (context, record) {
    return userOutput(context, record)
    .then(record => {
      if (record.friends)
        return store.adapter.find('user', [
          record.friends[record.friends.length - 1]
        ])
        .then(records => {
          record.lastFriend = records[0]
          return record
        })

      return record
    })
  }
  http.createServer(fortune.net.http(store)).listen(1337)
})
```

**Comment by xcapt** [comment]
1) Excellent, dereferencing is clear, thanks!

2) Without dereferencing, how do i get the link to lastFriend to work in the default HTML rendering? 

I have used the same example with:

`store.recordTypes.user.lastFriend = { link:'user' };

  const userOutput = store.transforms.user[1]

  store.transforms.user[1] = function (context, record) {
    if(record.friends) {
		record.lastFriend = record.friends[record.friends.length - 1]
	}
	return record;
}`

The link in user exists but when clicking on lastFriend, it does not show the user when following the link

**Comment by 0x8890** [comment]
The include doesn't work because the field is actually empty, it doesn't matter if it is set in the output transform. In order for it to work, you have to persist it, like so:

```js
store.transforms.user[0] = function (context, record, update) {
  var friends

  switch (context.request.method) {
  case 'create':
    friends = record.friends
    break
  case 'update':
    friends = update.replace.friends
    break
  }

  if (friends) record.lastFriend = friends[friends.length - 1]

  return update || record
}
```

**Comment by xcapt** [comment]
ah ok, thanks !
