### ISSUE TITLE
Adapter improvements

### ISSUE THREAD

**Issue by daliwali** [fortunejs/fortune#226]
Some incremental improvements to the Adapter:
- [x] Logical operators in `find` (#186).
- [x] ~~Add support for singular IDs, just a small opt-in improvement to aid usability.~~ no longer needed due to new instance methods.
- [ ] Add support for update & delete queries.

Regarding the last point, it could be like:

``` js
adapter.update(type, [ {
  // If ID is missing, expect options.
  options: {
    // Re-use `find` method options.
  },
  replace: { ... },
  push: { ... },
  pull: { ... },
  operate: { ... }
} ])
```

Delete API:

``` js
adapter.delete(type, [ {
  // Re-use `find` method options.
} ])
```

**Comment by voronianski** [comment]
@daliwali there are not so many information about `push` and `pull` objects in update. They are used only in updating relationships between records?

**Comment by voronianski** [comment]
@daliwali also I noticed that when doing for example `PUT` request, (e.g. `/users/d5049d443ae685531ced3624432fc67a`) input hook function is not called but response is always `204`. Is it a details of JSON API serializer? Or I should somehow manually return `404`?

**Comment by daliwali** [comment]
The input hook should always run, are you sure that record exists? Can you show me an example of that bug?

**Comment by voronianski** [comment]
@daliwali record exits, you can check this app - https://github.com/dhhb/api-next

```bash
# to run the app if you'd like
# but you'll need mongo instance running on port 27017
npm i
npm run start-dev
```

Input is called for `POST` and `PATCH` http methods only. On `PUT` it's not called and status `204` is responded.

**Comment by daliwali** [comment]
Actually it's because `PUT` is not supported at all. Nowhere in the JSON API spec tells you to use the `PUT` method. This was fixed in commit https://github.com/fortunejs/fortune-json-api/commit/f46dc7e565d7c82c59b4f678f2dcce35dafd7c13 and published as `2.1.1`.

**Comment by voronianski** [comment]
@daliwali but is it ok that unsupported method returns 204 instead of 404?

**Comment by daliwali** [comment]
It should return 415 Unsupported, which is the proper status code, not 404 as that would imply the URL doesn't exist.

**Comment by voronianski** [comment]
@daliwali then it's a bug?

**Comment by daliwali** [comment]
it has already been fixed [here](https://github.com/fortunejs/fortune-json-api/commit/f46dc7e565d7c82c59b4f678f2dcce35dafd7c13).

**Comment by voronianski** [comment]
@daliwali thanks

**Comment by daliwali** [comment]
>Add support for update & delete queries.

Probably not going to happen anytime soon, it would be rather unsafe to do in application code. The motivation for this was to be able to run DB migrations but I guess this can be handled outside of Fortune.
