### ISSUE TITLE
Links inside object

### ISSUE THREAD

**Issue by ashishtilara** [fortunejs/fortune#231]
Hi

I currently have a collection with data-structure which looks like
```
/users
{
    "id": ...
    "name": ...
    "links": {
        "posts": [...]
    }
}
```

Is there a way to achieve the same with fortune.js without changing data-structure?
I want to avoid the migration because few different systems read database directly expecting this structure, and I don't want to change them all.

Thank you
Ashish

**Comment by ashishtilara** [comment]
Also is there any place where I can find some examples for
- postProcessRequest, transformInput, transformOutput,
- integrating with Express and Passport / JWT

**Comment by 0x8890** [comment]
Are you using the default `JsonSerializer`? Then you can override `processResponse`:

```js
const { net: { JsonSerializer, Serializer } } = fortune
const CustomSerializer = JsonSerializer(Serializer)
CustomSerializer.prototype.processResponse = function (contextResponse, request, response) {
  // ...
  return contextResponse
}
```

Transform function should be pretty straightforward, examples might be too specific to use cases.

If you're using Express, Fortune can be used as a middleware:

```js
const app = express()
app.use(fortune.net.http(store, {
  // options
}))
```

**Comment by ashishtilara** [comment]
Thank you, any idea on how to handle links/relationships in object property

I tried doing

``` 
{
    "links": {
        type: Object,
        following: { link: 'user', inverse: 'links.followers', isArray: true }
    }
}
```
but it doesn't seem to work 😞

**Comment by 0x8890** [comment]
that won't work, and doesn't make sense from a schema design standpoint. if you just want to nest a link field inside of an object, it should be done in the serializer. take a look at [JSON API](http://jsonapi.org/) for an example of nesting and then [an implementation](https://github.com/fortunejs/fortune-json-api/blob/88b98a43b2f5b819c84334e5acc8afd98c1f2ceb/lib/helpers.js#L163). 

I think it is almost always a better decision to use a standard media type than to customize the default serializer to a non-standard format though.

**Comment by 0x8890** [comment]
Closing this, since it has already been answered.
