### ISSUE TITLE
Duplicate id's of relationships in database

### ISSUE THREAD

**Issue by Voles** [fortunejs/fortune#237]
I'm running into an issue where the database contains duplicate id's for relationships. I'm using Ember, the Ember JSONAPIAdapter, Fortune, Fortune JSON API and Fortune Postgres.

Below I'll try to describe the issue / reproduction path as good as possible. Please let me know if my assumptions are wrong or there's information missing.

**The problem**
When performing a PATCH request to the server, the relations object is always passed with the request.

The relations are updated correctly if it has no inverse property for the related defined. However, when an inverse property for the related model is specified, it will also update the that model.

**Example data model as defined in the store**

`````
product: {
    name: { type: String },
    shop: { link: 'shop', inverse: 'products' }
  },
shop: {
    name: { type: String },
    products: { link: 'product', inverse: 'shop', isArray: true }
  },
`````

**Reproduction path**

1. I'm sending a PATCH request for the product with id `product-1`. Only the name has changed.
The request will contain the `relationships` property with the following value for the `shop` property:  
`data: { id: shop-1, type: 'shop' }`  
I'm not sure if the relationship is supposed to be specified in this request, but that's how Ember's JSONAPISerializer does it.

2. The Fortune PostgreSQL adapter will run the `update()` method for the product model. Next it will run `update()` for the shop model.  
Because it's an array it will execute the following line: `set.push(`"${field}" = array_append("${field}", $${index})`)` See https://github.com/fortunejs/fortune-postgres/blob/master/lib/index.js#L408

3. However, there seems to be no check if that id is already present in the array. The result is that the array can contain duplicates.

4. Later on, when updating the shop-1 model, the request fails because of duplicate id's inside the `products` property.  

> Unhandled rejection ConflictError: Duplicate ID "product-1" in the field "products".

**Conclusion**
I hope I've described my problem clear enough. Looking forward to have your feedback. If I have a better understanding of what is going wrong, I can work on a fix.

Many thanks in advance!

**Comment by 0x8890** [comment]
This might be a bug within `fortune` itself, the adapter's update method should never be called with incorrect arguments.

There are lots of tests for updates: https://github.com/fortunejs/fortune/blob/master/test/integration/methods/update.js

If it really is a bug and hasn't been covered, it should also be added in the tests as well.

**Comment by Voles** [comment]
@0x8890 why do you think the update method is being called with incorrect arguments? Should the method be called at all for relations which are are already present in the db?

**Comment by 0x8890** [comment]
Most likely there is an incorrect calculation done somewhere in here: https://github.com/fortunejs/fortune/blob/master/lib/dispatch/update.js

What it does is try to update only what is necessary, and it seems there is something wrong because if the field is the same it shouldn't try to update the relationship.

If it isn't a core bug, then what I suspect is the issue is JSON API's requirement of string IDs isn't working with number IDs in Postgres.

**Comment by 0x8890** [comment]
It does not seem to be a problem in Fortune.js core. I added a demo to test it in a browser: https://github.com/fortunejs/fortune/blob/master/test/demo.js

Furthermore, I made some modifications to the above code to use Postgres and JSON:API, and still could not reproduce the error. This is what I tried:

```sh
curl -H 'Accept: application/vnd.api+json' -H 'Content-Type: application/vnd.api+json' -X PATCH -d '{"data":{"type":"animals","id":"1","relationships":{"owner":{"data":{"type":"users","id":"1"}}}}}' http://localhost:1337/animals/1
```

**Comment by Voles** [comment]
@0x8890 thanks for investigating! But I'm not sure how that demo.js file tests this behaviour? I can't see any relationships defined.

**Adapter options**
adapter: [
    postgresAdapter,
    {
      url: config.pgConnectionString,
      generatePrimaryKey: function () {
        function s4() {
          return Math.floor((1 + Math.random()) * 0x10000)
            .toString(16)
            .substring(1);
        }
        return s4() + s4() + '-' + s4() + '-' + s4() + '-' +
          s4() + '-' + s4() + s4() + s4();
      }
    }
  ],

**Serializer options**
serializers: [
      [jsonApi]
    ]

**Version numbers**
- fortune v3.4.3
- fortune-json-api v2.0.1
- fortune-postgres v1.4.3

**Comment by Voles** [comment]
@0x8890 I've updated Fortune to v3.5.4 which fixes this behaviour. Following commits contained the fix: https://github.com/fortunejs/fortune/compare/3.5.3...3.5.4

I should have updated before asking here :-/ Thanks very much for your work!

**Comment by 0x8890** [comment]
Hmm ok. Any reason you're not using `4.x` though? I would highly recommend using the latest version, the breaking change introduced by `4.0` is pretty trivial and won't affect you if you're not using WebSocket.

**Comment by Voles** [comment]
@0x8890 you're right. I've updated my application to the latest versions of all packages.

Is there a way I can donate to the project so I can support you for your work?

**Comment by 0x8890** [comment]
@Voles I would mostly welcome contributions to features and documentation, I'm not so interested in free software for money since it's mostly a labor of love for me. Also I re-use my own open source code in hobby projects and commercial projects as well.

>When applications are done well, they are just the really application-specific, brackish residue that can't be so easily abstracted away. All the nice, reusable components sublimate away onto github and npm where everybody can collaborate to advance the commons.

http://substack.net/how_I_write_modules

I typically don't implement features until I need them in my own projects, though sometimes I anticipate something I will need and it gets posted as an issue. This would be an example: https://github.com/fortunejs/fortune/issues/229
