### ISSUE TITLE
Update does not return 404 for unknown id

### ISSUE THREAD

**Issue by thomasthiebaud** [fortunejs/fortune#239]
Hej, 

I'm writing some tests for a jsonapi compliant API. But if I try to update an unknown resource, I get a 204 instead of a 404. Here is my test :

```
const body = { 
  data: { 
    id: 'abcd',
    type: 'customers',
    attributes: { 
      name: 'Thomas', 
      address: 'Lund', 
      role: 'distributor' 
    } 
  } 
}

chai
  .request(server)
  .patch('/customers/abcd')
  .set('Content-Type', 'application/vnd.api+json')
  .send(body)
  .end(function (err, res) {
    expect(res).to.have.status(404);
    done();
  });
```

And here is the result I get :

```
AssertionError: expected { Object (domain, _events, ...) } to have status code 404 but got 204
```

Did I miss something ? Or is it a bug ?

**Comment by 0x8890** [comment]
This is actually a bug, though it may be in the JSON API serializer and not here.

**Comment by 0x8890** [comment]
The bug has been fixed: https://github.com/fortunejs/fortune/commit/3be4d3e603fa0344d8653df4ccc737dafd4fbe25

There is now a test so it shouldn't happen again.

**Comment by thomasthiebaud** [comment]
Thanks
