### ISSUE TITLE
Create data with relationship works with null id

### ISSUE THREAD

**Issue by thomasthiebaud** [fortunejs/fortune#240]
Hej,

if I send a POST request with something like this

```
{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": null
    }
  }
}
```

I get a 201, but I am expecting an error (400 for example). When I check the database there is no constraints on the table for the foreign key. Is there a way to add constraints on the database or validate the input ?

Thomas

**Comment by 0x8890** [comment]
I just tried to create a resource including a relationships object like in your example:

```json
{
  "relationships": {
    "owner": null
  }
}
```

Which resulted in a 400 error. However, this relationships object works, and is valid:

```json
{
  "relationships": {
    "owner": { "data": null }
  }
}
```

If you are using the Postgres adapter, there is the [`useForeignKey` option](https://github.com/fortunejs/fortune-postgres#options) which is not enabled by default. The reason why is explained [here](http://fortune.js.org/concepts/#graph-database). Basically because it doesn't help much if referential integrity is handled at the application level, and also because [it's slower to use a join table](https://gist.github.com/joevandyk/031cf5812bd656887623).

**Comment by thomasthiebaud** [comment]
Thanks for the answer. There is something I don't get : your second example breaks the referential integrity. Here is a more concrete example.

    const user = {
        email: String,
        password: String,
        phone: String,
        avatar: String,
        role: String,
        customer: ['customer', 'users'],
    };

    const customer = {
        name: String,
        address: String,
        apikey: String,
        role: String,
        users: [Array('user'), 'customer'],
    };

    const adapter = [
        postgresAdapter, {
            url: `postgres://${config.get('DATABASE_USER')}:${config.get('DATABASE_PASSWORD')}@${config.get('DATABASE_HOST')}:${5432}/${config.get('DATABASE_NAME')}`,
            useForeignKeys: true,
            generatePrimaryKey: () => uuid.v4(),
        },
    ];

    const store = fortune({
        // Put models here
        customer,
        user,
    }, {
        adapter,
    });

Then if I POST this request 
```
{ 
  data: { 
    type: 'users',
    attributes: { 
      email: 'invalid@combain.com',
      password: 'invalid',
      phone: 'invalid',
      avatar: 'invalid',
      role: 'admin' 
    },
    relationships: { 
      customer: { 
        data: null 
      } 
    },
    jsonapi: { 
      version: '1.0'
    } 
}
```

I have a 201 and in the database I have something like

![selection_001](https://cloud.githubusercontent.com/assets/3715715/18776581/7a543a00-816a-11e6-8789-cc0a52861891.png)
![selection_002](https://cloud.githubusercontent.com/assets/3715715/18776582/7a56755e-816a-11e6-94b2-1e04d7647a83.png)

Where can I refuse to insert a null reference ?

**Comment by 0x8890** [comment]
Well there are two ways to do that: either [modify the database schema](http://stackoverflow.com/questions/512451/how-can-i-add-a-column-to-a-postgresql-database-that-doesnt-allow-nulls) so that the column is required, or specify an input hook.

The input hook would look like:

```js
const { errors: { BadRequestError } } = fortune

function userInput (context, record, update) {
  switch (context.request.method) {
    case 'create':
      if (!record.customer)
        throw new BadRequestError('A customer is required.')
      break
    case 'update':
      if (update.replace && update.replace.customer === null)
        throw new BadRequestError('Can not unset customer.')
      break
  }
}
```

To tell fortune to use it, it should be passed into the constructor function:

```js
fortune(recordTypes, {
  hooks: {
    // Order is input, output
    user: [ userInput, null ]
  }
})
```

A null value in a foreign key column is valid, according to [this answer](http://stackoverflow.com/questions/7573590/can-a-foreign-key-be-null-and-or-duplicate).

**Comment by thomasthiebaud** [comment]
Thanks, I will try both solutions and pick one.

**Comment by thomasthiebaud** [comment]
I can't successfully register the hook. I have an undefined value.

```
const store = fortune({
  // Put models here
  customer,
  device,
  user,
}, {
  adapter,
  hooks: {
    customer: [() => console.log('Input hook'), null],
  },
});
```

And I get

> TypeError: Cannot read property 'length' of undefined
    at map (node_modules/fortune/lib/common/array/map.js:13:24)
    at node_modules/fortune/lib/dispatch/delete.js:71:19
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by 0x8890** [comment]
That looks correct. Actually you may have discovered an edge case bug: when a delete request is issued without IDs it does not seem to find any records. This should not be allowed to do except directly via the adapter, so it seems to be a messaging problem as well.

**Comment by 0x8890** [comment]
It should be fixed in https://github.com/fortunejs/fortune/commit/580587a9a73402eed239859d5779c07f7c555270

Basically the delete without IDs can't work properly via request, so it is just disabled now.

**Comment by thomasthiebaud** [comment]
Or it can be fixed by updating the `map` function to 

```
module.exports = function map (array, fn) {
  var i, j, k = [], l = 0

  if (!array)
    return k

  for (i = 0, j = array.length; i < j; i++)
    k[l++] = fn(array[i], i, array)

  return k
}
```

I used to use delete without ID to truncate tables in my tests.

**Comment by thomasthiebaud** [comment]
It works without ids if I directly call the adapter. So I only have to update

    store.delete(/* ... */)

to

    store.adapter.delete(/* ... */)

Thanks a lot !

**Comment by 0x8890** [comment]
Yep, that was the change. Allowing a delete request without IDs was dangerous because it could potentially drop all records without running the input hook, so it was made more explicit by calling the adapter method directly.

**Comment by thomasthiebaud** [comment]
Hej, sometimes (around 50% of the time9 I have an error in my truncate function which is this one 

```
function truncate() {
  return store.adapter.delete('user')
    .then(() => store.adapter.delete('customer'));
}
```

The error is 

> TypeError: Cannot read property 'query' of undefined
    at Promise (node_modules/fortune-postgres/lib/index.js:485:13)
    at PostgreSQLAdapter.delete (node_modules/fortune-postgres/lib/index.js:484:12)
    at Object.truncate (test/utils/database.js:32:30)
    at Context.<anonymous> (test/api/customer.spec.js:21:21)

**Comment by 0x8890** [comment]
The only way that is possible is if you are disconnected already: https://github.com/fortunejs/fortune-postgres/blob/4f827294bf5b100313c588bdebf4651abd11d030/lib/index.js#L152

Are you sure you are not calling disconnect somewhere?

**Comment by thomasthiebaud** [comment]
I never called `disconnect` (I double checked again). And I manually connect like this :

```
  before(function () {
    return store.connect();
  });

  beforeEach(function () {
    return database.truncate();
  });
```

**Comment by 0x8890** [comment]
Are you sure that the test runner resolves Promises? It is possible that both the `connect` and `delete` methods are called simultaneously. If that is the case then you have to chain the Promises yourself:

```js
store.connect().then(() => database.truncate())
```

**Comment by thomasthiebaud** [comment]
I chain myself the Promises and it works ! I will close this issue and try to find another way than calling the connect method into the `beforeEach` hook.
