### ISSUE TITLE
Split up packages

### ISSUE THREAD

**Issue by sapeien** [fortunejs/fortune#245]
It might be a good time to completely separate the functionality provided by Fortune.js into smaller modules.

Here's what I think can be extracted:

- `fortune` will remain the core module. the memory adapter will stay here since it is rather trivial.
- `fortune-http` contains the http implementation, including the json + html + formdata + urlencoded serializers.
- `fortune-ws` contains the websocket server + client implementation.
- `fortune-indexeddb` contains the indexeddb adapter.

This makes the core functionality very clear and drastically decreases dependencies:

- DB Adapter interface
- built-in memory adapter
- type checking
- relationship updates
- referential integrity
- I/O hooks

at this minimal level of functionality, it is just an in-memory db with first class support for relations.

I don't think keeping all packages in the same repository is a good idea, I would rather keep things separate.

this would necessarily be a major version bump.

**Comment by kketch** [comment]
👍 
From what I understand the functionnality included today with the fortune package will require at least to install new packages ? This seems like a major refactor to me and you should I think introduce a new major version bump

**Comment by 0x8890** [comment]
yes, it will be a major version bump.

**Comment by kketch** [comment]
@0x8890 I would be happy to help you with this migration should you need some help

**Comment by sapeien** [comment]
Done in #248
