### ISSUE TITLE
Is Object supported ?

### ISSUE THREAD

**Issue by thomasthiebaud** [fortunejs/fortune#249]
I would like to define an object field in one of mine model. The documentation says 

> The allowed native types are String, Number, Boolean, Date, Object, and Buffer. Note that the Object type should be a JSON serializable object that may be persisted.

so here is my model 

```
const record = {
  date: String,
  value: Object,
  device: ['device', 'records'],
};
```

but when I do a GET request, I get

```
"data": [
    {
      "attributes": {
        "date": "10/31/2016, 9:40:39 AM"
        "value": "{\"geo\":\"3.1394, 159.91106, 8100.99357\",\"saovpoz\":61}"
      }
      // More fields
    }
]
```

but I expected something like

```
"data": [
    {
      "attributes": {
        "date": "10/31/2016, 9:40:39 AM"
        "value": {
          "geo": "3.1394, 159.91106, 8100.99357"
          "saovpoz": 61
        }
      }
      // More fields
    }
]
```

Why do I get a String and not a json object ? Did I miss something ?

**Comment by thomasthiebaud** [comment]
I drop all the tables and it is now working.

**Comment by sapeien** [comment]
If you're using the Postgres adapter, it will not do migrations automatically. Changing types of columns is potentially destructive.

**Comment by thomasthiebaud** [comment]
Thanks for your answer. I saw that ;)
