### ISSUE TITLE
Replacing only one serializer

### ISSUE THREAD

**Issue by mbavio** [fortunejs/fortune#250]
Hey, I'm trying to use the [jsonapi-serializer](https://github.com/fortunejs/fortune-json-api) instead of the default json one, but I don't want to loose the amazing API admin for free that fortune-http offers by default. So I tried doing this but it didnt work:

```
app.use(createListener(store, {
    serializers: [
        [ jsonApiSerializer ],
        [ htmlSerializer ],
        [ formSerializer.formData ],
        [ formSerializer.formUrlEncoded ]
    ]
});
```

If I keep only the `jsonApiSerializer` it works like expected but no html edit anymore, and if I remove the whole thing it also works but with default `jsonSerializer` which is not an option for me.

I'm using express btw.

Any help into how to achieve this? Thanks!

**Comment by sapeien** [comment]
That looks correct actually, it's pretty much [the same thing I did](https://github.com/sapeien/imagenote/blob/d2dcb0517da6788a505fdb522042b28caa8a9a15/lib/app.js#L24-L37).

What problem did you encounter?

**Comment by mbavio** [comment]
<img width="568" alt="screen shot 2016-11-10 at 1 07 07 pm" src="https://cloud.githubusercontent.com/assets/5664/20184208/a4a526fa-a746-11e6-9bb9-fe0309e3f9d9.png">

**Comment by mbavio** [comment]
@sapeien Would you like for me to share the full code that try to instantiate the server?

**Comment by sapeien** [comment]
I think I know what the problem is: the keys have changed since the major version update to v5.

The docs are up to date: http://fortune.js.org/api/#fortunehttp-createlistener

You will want these keys:

- `HtmlSerializer`
- `FormDataSerializer`
- `FormUrlEncodedSerializer`

**Comment by mbavio** [comment]
Oh, but I think I was already doing that:

```
const fortuneHttp = require('fortune-http');
const httpSerializer = fortuneHttp.Serializer;
const jsonSerializer = fortuneHttp.JsonSerializer;
const htmlSerializer = fortuneHttp.HtmlSerializer;
const formSerializer = fortuneHttp.FormDataSerializer;
```

**Comment by mbavio** [comment]
More context to help:

```
const express = require('express');
const helmet = require('helmet');
const cors = require('cors');
const fortune = require('fortune');
const fortuneHttp = require('fortune-http');
const httpSerializer = fortuneHttp.Serializer;
const jsonSerializer = fortuneHttp.JsonSerializer;
const htmlSerializer = fortuneHttp.HtmlSerializer;
const formDataSerializer = fortuneHttp.FormDataSerializer;
const formEncodedSerializer = fortuneHttp.FormEncodedSerializer;
const jsonApiSerializer = require('fortune-json-api');

const app = express();
const store = require('./store');

app.use(helmet());
app.use(cors());
app.use(fortuneHttp(store, {
  serializers: [
    [ jsonApiSerializer ],
    [ htmlSerializer ],
    [ formDataSerializer ],
    [ formEncodedSerializer ]
  ]
}));



app.use(function(err, req, res, next) {
  if (err) {
    res.status(500).send(err);
  }
});

store.connect().then(() => {
  app.listen(5000, function() {
    console.log('App running on port 5000');
  });
})
```

**Comment by sapeien** [comment]
Maybe do a sanity check:

```js
const serializers = [
  jsonApiSerializer,
  htmlSerializer,
  formDataSerializer,
  formEncodedSerializer
]

serializers.forEach(x => console.log(typeof x))
```

**Comment by mbavio** [comment]
Great suggestion. It works like charm now, name for the last serializer is `FormUrlEncodedSerializer`, not `FormEncodedSerializer`. 😀

Thanks for your help, @sapeien, gonna close the issue now although it's a decent example for all those asking for Express integration!

**Comment by sapeien** [comment]
Thanks for opening this issue, I created a [follow-up](https://github.com/fortunejs/fortune-http/issues/1) for improving the error message in this case.

**Comment by mbavio** [comment]
@sapeien fantastic work in here, buddy. Keep it coming!
