### ISSUE TITLE
Neo4j Adapter

### ISSUE THREAD

**Issue by sapeien** [fortunejs/fortune#253]
There is now a Node.js driver for Neo4j which uses their Bolt protocol, which is much better than the HTTP API they had before.

https://www.npmjs.com/package/neo4j-driver

**Comment by sapeien** [comment]
I don't have any interest in using Neo4j anymore, but I'd be happy to support any efforts to write an adapter for it.

**Comment by adnasa** [comment]
I've looked into this.
I still have a long way to go since I don't support buffers just yet.
