### ISSUE TITLE
Case insensitive find

### ISSUE THREAD

**Issue by Voles** [fortunejs/fortune#259]
I'm working on an application where users can login. During the implementation of the login-endpoint, I wanted to perform a case insensitive search.

Eg. finding a user with email address 'foo@bar.com' should also match 'FOO@BAR.COM'.

Is there a way to perform a case insensitive search using find? Or another way how this can be performed?

**Comment by sapeien** [comment]
There's no built-in way to do that. However it looks like since you're dealing with email addresses, you could safely normalize inputs to be lowercase.

**Comment by Voles** [comment]
@sapeien thanks for your quick response! I'll perform a migration for existing users and make sure the email addresses are stored lowercase.

Thanks again 🌻
