### ISSUE TITLE
Custom types error

### ISSUE THREAD

**Issue by voronianski** [fortunejs/fortune#265]
I'm upgrading to latest fortune and have following error:

```bash
Error: The "type" on "email" must inherit from a valid native type.
```

However it's function:

```js
email: {
  type: types.Email
},
```

```js
export const Email = (value) => {
  return isEmail(value.trim());
};
```

What is wrong here?

**Comment by voronianski** [comment]
@daliwali ok, I've found this line in docs... IMHO this looks a bit weird and verbose:

```
function Integer (x) { return (x | 0) === x }
Integer.prototype = Object.create(Number.prototype)
```

**Comment by daliwali** [comment]
Yep, actually it should be a bit simpler. I've updated the docs in commit https://github.com/fortunejs/fortune/commit/622ce9014e1896f3a179351b54bf82d6e133006b so that it looks like:

```js
Integer.prototype = new Number()
```
