### ISSUE TITLE
Clearify on inverse

### ISSUE THREAD

**Issue by voronianski** [fortunejs/fortune#269]
I just want to clearify if inverse functionality is working fine for my case:

Example:

```js
// user has
articles: [Array('article'), 'author']

// article has
author: ['user', 'articles']
```

In responses I see `relantionships` key. Though `data` key contains only `type` and `id`:

```json
"relationships": {
  "articles": {
    "links": {
      "self": "/users/2c2664a627f3a7a3db7524bdbc4a38fd/relationships/articles",
      "related": "/users/2c2664a627f3a7a3db7524bdbc4a38fd/articles"
    },
    "data": [{
      "type": "articles",
      "id": "9d0fca7fb8bfc1454057d95b5e6d044a"
    }]
  }
}
```

**Is it by design? For additional data I need to query this type by id directly, correct?**

**Comment by daliwali** [comment]
Can you please open issues on the right repository? `fortune-json-api` is over here: https://github.com/fortunejs/fortune-json-api

Everything is implemented according to the JSON API spec. There are a few strategies you can use to get this related data:

- using the include parameter
- fetching each article individually
- using the related link

How you do it is up to you.

**Comment by voronianski** [comment]
@daliwali thanks, `include` works perfectly!
