### ISSUE TITLE
Conditionally return records in output function

### ISSUE THREAD

**Issue by voronianski** [fortunejs/fortune#270]
Is it possible to conditionally return value from output function? Use case - there is array of articles, all of them have flag `draft`. If `draft: true` we need to filter out this record and return it only in the case authentication token is present in the request. I tried something similar to below but it doesn't work:

```js
  async output(context, record) {
    if (record.draft) {
      return null;
    }

    return record;
  }
```

**Comment by daliwali** [comment]
It's not allowed to return `null`, though I see why you would want to do it. In general it's not a good idea because if a certain number of records are expected, returning less may lead to problems.

If you have some authentication logic then you could set `match: { draft: false }` if requested type is article and the user is unauthenticated.

**Comment by voronianski** [comment]
@daliwali 

> If you have some authentication logic then you could set match: { draft: false } if requested type is article and the user is unauthenticated.

You mean by making `context.transaction.find` call inside output function?

**Comment by daliwali** [comment]
I mean modifying the request before it is called. For example,

```js
const internalRequest = store.request

store.request = function (options) {
  if (options.meta.headers['authorization'] !== 'secret')
    if (options.type === 'article')
      options.options.match = { draft: false }

  return internalRequest.call(this, options)
}
```

**Comment by voronianski** [comment]
@daliwali thanks, didn't think about this option, though the place looks a bit not obvious, I'll need to find a way how to add this logic inside article type object and then patch store request with it.

**Comment by daliwali** [comment]
@voronianski this would be for preventing records from being read, so you wouldn't have to think about whether a client is allowed to read a record. This shouldn't be done in an output hook because at that point, the record has already been read unnecessarily.

>I'll need to find a way how to add this logic inside article type object

What did you mean by this?

**Comment by voronianski** [comment]
@daliwali 

> I'll need to find a way how to add this logic inside article type object
What did you mean by this?

I was thinking of adding some function `beforeRequest` to record type object https://github.com/dhhb/api-next/blob/master/src/v1/types/article.js#L14 and then inside store file (https://github.com/dhhb/api-next/blob/master/src/v1/store.js) do something like:

```js

if (isFunction(type.beforeRequest)) {
  beforeRequestHooks.push(type.beforeRequest);
}

//...

store.request = function (options) {
  beforeRequestHooks.forEach(hook => {
    hook(options); // handle async in some way
  });

  return internalRequest.call(this, options);
};
```

**Comment by voronianski** [comment]
@daliwali did it like this:

- https://github.com/dhhb/api-next/blob/master/src/v1/store.js#L50-L61
- https://github.com/dhhb/api-next/blob/master/src/v1/types/article.js#L32-L46
