### ISSUE TITLE
What am I supposed to do with Child.__Parent_child_inverse?

### ISSUE THREAD

**Issue by wolfgang42** [fortunejs/fortune#272]
I have the following store (simplified for clarity), used with `fortune-json-api` (with inflection disabled) and a custom adapter:
```javascript
const store = fortune({
    Product: {
        collection: {link: 'Collection'},
    },
    Collection: {
        name: String,
    },
})
```

When I try to update a Product, I get a call to `Adapter.find()` which requests the field `__Product_collection_inverse` on the Collection with the relevant ID. I've found that this call is coming from [`checkLinks()`](https://github.com/fortunejs/fortune/blob/ba7e41370c02b2f48c5e9ea3aad833c31907b1c2/lib/dispatch/check_links.js#L28), but I can't tell if anything is actually using the result. What should I be returning for this key?

This seems like something that would be documented somewhere, but I can't find it.

**Comment by daliwali** [comment]
This is actually an internal implementation detail called the *denormalized inverse key*, it is described in a comment: https://github.com/fortunejs/fortune/blob/632a27bd994f529b3e28254032c939e92f3c5ed2/lib/record_type/ensure_types.js#L59-L61

It will always be named as ``__${type}_${field}_inverse``, and is intended to be written and read only by Fortune.js itself. This is required for bi-directional links to work.

If you haven't been writing to this inverse field, then it would make sense to either populate it manually or change the field from a `link` to a primitive type.

This field is intended to be non-enumerable so clients don't read it, and when introspecting fields it is necessary to use `Object.getOwnPropertyNames` to iterate over it, example: https://github.com/fortunejs/fortune-postgres/blob/26114af75bf68fee4f89acf3cbaf2aef22a47ca0/lib/index.js#L136-L141

**Comment by wolfgang42** [comment]
Hmmm, I'm still confused.

The comment you linked to says that this field "exists in the data store". Is a *data store* the other half of what my adapter is talking to (in my case a SQL database), or is it something internal to Fortune?

The only place this inverse field is showing up is the `find Collection` when I write to a Product (I don't see it when I create or update a Collection). What and where should I be populating it with? I want the field to be a `link` so that it shows up as a relationship on the Product (in particular so I can get `/Product?include=Collection`), but I don't really care what it looks like on the Collection end.

**Comment by daliwali** [comment]
In your case, it needs to be a column in the SQL database. What the PostgreSQL adapter does is set up this column automatically.

If your data model contains an array link (to-many relationship), you may lose referential integrity if one of the linked records gets deleted. Fortune internally uses this denormalized inverse key to efficiently write to the other side of the link.

If the SQL database you use doesn't support array column types such as MySQL, then Fortune.js might not be a good fit. I would advise to use either the PostgreSQL adapter or modify it to fit your RDMS of choice.

**Comment by wolfgang42** [comment]
I've just discovered that it gets updated on the Collection when I update the collection of a Product, so that at least is starting to make sense.

I don't have an array link, just a scalar link from a Product to a single Collection. Given that this is the case, can my adapter simply ignore any attempts to work with these denormalized inverse keys? Referential integrity will be enforced by the underlying database when possible.

I've written a custom adapter because this is an interface to a legacy database with a bizarre and byzantine schema, so the adapter does things like updating a different table depending on which field was changed. Fortune is working quite well for the task thus far, other than this one issue.

**Comment by daliwali** [comment]
>Given that this is the case, can my adapter simply ignore any attempts to work with these denormalized inverse keys? Referential integrity will be enforced by the underlying database when possible.

You know what your legacy database does better than I do, so depending on what the database does, it's possible to just ignore denormalized inverse keys, or even short-circuit this request so that it never actually touches the database.

**Comment by wolfgang42** [comment]
Since I've gotten this working I'm going to close the issue. Thank you for your help!
