### ISSUE TITLE
Request body data already received

### ISSUE THREAD

**Issue by Voles** [fortunejs/fortune#273]
I'm using Fortune with Express, the JSON API adapter and a PostgreSQL database. Some API endpoints require authentication, for which I have added an extra Express middleware layer.

**My usecase**
```
const listener = fortune.net
  .http(store, {
    serializers: [
      [jsonApi]
    ]
  });

app.use('/user', userRoutes);
app.use(listener);
```

Here `/user` is an endpoint provided by Fortune. Because I want to check if the user has the right permissions, I'm adding the `userRoutes` middleware here.

The problem is that I read the request's body in the `userRoutes` middleware layer. Which breaks Fortune's logic for reading that same data.

I have solved this by adding a check if `request.body` has already been set. If not, Fortune will listen to the request's data coming in.

See https://github.com/Voles/fortune/commit/26db963ee09d5e18b44ff1d818b4a9b7d6186409

I'm sure other people must have has similar issues. Is this something you're considering adding to the core, or should it be solved in an other way?

Thanks in advance! 🌻

**Comment by daliwali** [comment]
There's no built-in way to "unread" a stream after it has finished reading. But there's also no rule that says you can't do it yourself:

```js
function unreadRequestMiddleware (req, res, next) {
  var chunk = Buffer.from(JSON.stringify(req.body))

  req.on = function (name, cb) {
    switch (name) {
      case 'data': return cb(chunk)
      case 'end': return cb()
    }
  }
  next()
}
```

There is no need to fork the codebase to get this functionality.

**Comment by daliwali** [comment]
By the way, this probably can't be done in a generic fashion in `fortune-http`. There are two things missing:

- No public API for checking the state of a readable stream.
- No reliable method for passing the entire output of the readable stream (`req.body` is non-standard and specific to express, and I'd rather not add framework-specific code).
