### ISSUE TITLE
How to use store.request({ include: [] }) ?

### ISSUE THREAD

**Issue by Myshkouski** [fortunejs/fortune#279]
Here is my code:
```
const Fortune = require('fortune')
const MongoDb = require('fortune-mongodb')

const { log, error } = console

const typeMap = {
	person: 'persons',
	organisation: 'organisations'
}

const store = Fortune({
	person: {
		name: String,
		employers: [Array('organisation'), 'employees']
	},
	organisation: {
		name: String,
		employees: [Array('person'), 'employers']
	}
}, {
	adapter: [
		MongoDb,
		{
			url: 'mongodb://localhost:61746/fortune',
			typeMap
		}
	]
})

store
	.request({
		method: 'find',
		type: 'organisation',
		include: [ /* ????????????????????????????? */ ]
	})

	/*Expect:
		[
			{
				name: 'Apple',
				employees: [
					{ name: 'Bob' },
					{ name: 'Alice' }
				],
			},
			{
				name: 'Google',
				employees: [
					{ name: 'John' },
					{ name: 'Kate' }
				]
			}
		]*/

	.then(res => log(res.payload.records))
	.catch(error)
```
Could you explain what should be placed in 'include' property?
None of the following options is working:
```
// ...
const { defaults } = require('lodash')

const options = {
	method: 'find',
	type: 'organisation'
}

const attempts = [
	['employees', 'name'],

	['employees', {name: true}],

	['employees', ['name'] ],

	[ ['employees', 'name'] ],

	[ ['employees', { name: true }] ]

	// ???
]

attempts
	//merge options and 'include' property
	.map(include => defaults({ include }, options))
	
	.reduce((promise, options) => {
		return promise
			.then(() => {
				return store.request(options)
			})
			.then(res => {
				log(
					'done', options.include, ':', 
					...res.payload.records.map(rec => rec.employees) // ids only => problem
				)
			})
			.catch(err => {
				error(
					'failed with', options.include, ':', 
					err.message
				)
			})
	}, Promise.resolve())
```
Output:
> done [ 'employees', 'name' ] : [ 'SfKQM1X3+XvRQSjI3Byf' ]
> done [ 'employees', { name: true } ] : [ 'SfKQM1X3+XvRQSjI3Byf' ]
> failed [ 'employees', [ 'name' ] ] : The field "name" does not define a link.
> failed [ [ 'employees', 'name' ] ] : The field "name" does not define a link.
> done [ [ 'employees', { name: true } ] ] : [ 'SfKQM1X3+XvRQSjI3Byf' ]

Thanks in advance!.

**Comment by daliwali** [comment]
`include` is a 3-dimensional array. It is documented [here](http://fortune.js.org/api/#fortune-request).

1. What relationships to include.
2. How deep those relationships are.
3. If applicable, apply a query at this depth.

In your case, it would be:

```js
[ [ ['employees', { fields: { name: true } } ] ] ]
```

This could be simplified, in case all of the dimensions aren't really used, I haven't gotten around to that yet.

**Comment by Myshkouski** [comment]
The following request:
```
store
	.request({
		method: 'find',
		type: 'organisation',
		include: [ [ [ 'employees', { fields: { name: true } } ] ] ]
	})
	.then(res => log(res.payload.records))
	.catch(error)
```
... does not result as expected:
> [ { id: '8QIlAfhkde1J+KiD8cVu',
>    name: 'Google',
>    employees: [ 'SfKQM1X3+XvRQSjI3Byf' ] },
>  count: 1 ]

Really confused about it, any suggestions for a noob like me?

**Comment by daliwali** [comment]
The records returned from `include` are located on `result.payload.include`, not `records`. They are treated separately from the main results. This is also documented [here](http://fortune.js.org/api/#fortune-request).

If you read the docs, you wouldn't need to ask :^)

**Comment by daliwali** [comment]
Thanks to your question, I've updated the `include` format to be more flexible, and now the minimal case is possible. https://github.com/fortunejs/fortune/commit/3f5281e2a7eba300da96fe41f0c56353262b3e6e

**Comment by Myshkouski** [comment]
Thank you for feedback and update for that great module!

**Comment by brandonmikeska** [comment]
@gr0uch trying to pass in the includes using insomnia or postman while writing a custom adapter. Trying to figure out how to pass this in while testing.

You mentioned it needs to look like this:

```[ [ ['employees', { fields: { name: true } } ] ] ]```

Do you know how to pass in the includes but also filter by fields? 

The JSON API Spec example page: https://jsonapi.org/examples/ shows this:

GET /articles?include=author&fields[articles]=title,body,author&fields[people]=name 

Any help would be great!

**Comment by gr0uch** [comment]
@brandonmikeska you mean like this?
https://github.com/fortunejs/fortune/blob/b105b7509ff863b37f77e2d3ec16235985ee4826/test/integration/methods/find.js#L89-L103

that's a question that belongs in the json-api serializer. i don't remember exactly but it's definitely possible.

**Comment by brandonmikeska** [comment]
Apologies, I will ask over in that repo! Trying to find out how to pass it in through query parameters so it builds out an array like so! Thank you
