### ISSUE TITLE
Need help on documentation?

### ISSUE THREAD

**Issue by FilipNest** [fortunejs/fortune#280]
Hi! I'm moving a big CMS project over to Fortune and the lack of quick, easy to understand/reference documentation makes it a bit tough to get into.

I think it's all there in various places but could be a bit clearer. Want some help?

**Comment by FilipNest** [comment]
Going to close this as after a read through the whole website API docs it does cover pretty much everything. Might just be me. If you ever want help writing docs or making them clearer give me a shout.

**Comment by daliwali** [comment]
The API docs are generated from JSDoc-style comments in the source code, and there's quite a few inline comments as well.

There's a guide that is intentionally a bit short. I'm well aware that the docs could use some clarification. What part was confusing?

**Comment by FilipNest** [comment]
There was just a lot of skipping back and forth and reading comments. I'll report back once I've got a full grasp of it and then maybe contribute some help if I spot any needed. This comment was a bit premature. Sorry! Looks like a fab library by the way. Will certainly try to contribute some way whether it's code or words. Thanks.
