### ISSUE TITLE
README Question

### ISSUE THREAD

**Issue by sprjr** [fortunejs/fortune#281]
Hello! Just checking out this project per a recommendation from a co-worker, so started with just the docs. Was wondering if I was missing the syntax here:

```
following: [ Array('user'), 'followers' ],
followers: [ Array('user'), 'following' ],
```

It _appears_ that the second argument for each array is mixed up - but then I thought maybe these relationships themselves are related through this?

Feel free to close if thats what is intended, but thought I'd ask! Looking forward to checking this out further either way! :)

**Comment by jmeas** [comment]
@sprjr , the example is correct here. The [documentation for the Fortune constructor](http://fortune.js.org/api/#fortune-constructor) touches on this briefly. These are references to the inverse field of the relationship.

In this case, `following` and `followers` refer to the same sort of data, but referenced from two different perspectives. tl;dr, anytime you set up a relationship, you should define it in both directions.

Another example would be that each parent has `children`, and each child has `parents`.

It can be confusing at first. Let me know if that helps. If not, I can try to explain it more thoroughly.

**Comment by daliwali** [comment]
Just wanted to add that the above notation is shorthand for the more explicit version:

```js
{
  user: {
    followers: { link: 'user', isArray: true, inverse: 'following' }
    following: { link: 'user', isArray: true, inverse: 'followers' }
  }
}
```

Without the `inverse` keyword, it appears repetitive, but it is not. Fortune.js needs to know the inverse of links because it can be ambiguous. i.e., if another field `friends` was added with a link to users, you would have to specify the inverse as `friends` to indicate a reflexive relationship, otherwise it's unknown whether that link is related to followers or following. I hope that clears things up.

**Comment by sprjr** [comment]
@daliwali thanks for clarifying. I had a hunch that this was an inverse relationship - it just wasn't very intuitive / clear to me at first glance. I was able to chat with James offline, and he had an example (I think he used cat/person) that had relationships that were not simply swapped words so that was more clear (e.g. a person can have a cat, and that relationship is an `owner` but when a cat has a person its relationship is `pet`).

Anyway, sorry that the shorthand threw me off - I read the quick start part and then asked questions before reading further on in the docs.

Thanks again!

**Comment by jmeas** [comment]
Sounds like this is resolved, so I'll close this for now. Feel free to reopen if you think we can help further @sprjr !
