### ISSUE TITLE
New fortune adapter for Google Cloud Datastore

### ISSUE THREAD

**Issue by patrinhani-ciandt** [fortunejs/fortune#284]
Hey guys, just posting here to announce that i've published a new fortune adapter for Google Cloud Datastore.

It's is available on: 
Source: https://github.com/patrinhani-ciandt/fortune-datastore
NPM Package: https://www.npmjs.com/package/fortune-datastore

Would be awesome to have your contributions and feedbacks there!

Thank you all!

**Comment by daliwali** [comment]
Cool! Do the tests pass and are there any tests running in CI?

I just did some quick searching and found that it supports transactions: https://cloud.google.com/datastore/docs/concepts/transactions

The Postgres adapter implements transactions as well, for example. It is optional but would make sense to implement if the database supports transactions.

I'd like to include it in the plugins doc.

**Comment by patrinhani-ciandt** [comment]
Thank you @daliwali , i'm trying to add some datastore emulator to run the Tests in CI. 

About the transactions, i'm still figuring out the best way to implement that!

Thank you for your comment!

**Comment by patrinhani-ciandt** [comment]
Hey @daliwali, how are you? I've configured the CI to running the tests ... My repo is already updated with that ...
https://github.com/patrinhani-ciandt/fortune-datastore
https://travis-ci.org/patrinhani-ciandt/fortune-datastore

**Comment by daliwali** [comment]
I added it to the docs: https://github.com/fortunejs/fortune/commit/c01cc64de860ae96887360f6c88361e45dfb2814

Cheers!
