### ISSUE TITLE
Expose transactions

### ISSUE THREAD

**Issue by daliwali** [fortunejs/fortune#285]
Right now each request creates a new transaction. This is fine, but it should also be possible to pass in a transaction to re-use it across multiple requests.

This would open up transactions to clients.

**Comment by daliwali** [comment]
Done https://github.com/fortunejs/fortune/commit/43f31c3045156f8f6c52e3a12230019022b11dde

**Comment by dalane** [comment]
@daliwali, can you provide an example on how to use the transaction across multiple client requests? It appears that there are no tests to demonstrate how this works.

**Comment by daliwali** [comment]
It's documented: http://fortune.js.org/api/#fortune-request

Example:

```js
let transaction;

store.adapter.beginTransaction()
  .then(result => {
    transaction = result
    store.request({ transaction, ... })
  })
  .then(response => {
    transaction.endTransaction()
    return response
  })
```
