### ISSUE TITLE
Should ensureTypes return Symbols?

### ISSUE THREAD

**Issue by bpinney** [fortunejs/fortune#291]
https://github.com/fortunejs/fortune/blob/93bd5d9d1286b4839520a7e2aba26f7f01ac553d/lib/record_type/ensure_types.js#L64
https://github.com/fortunejs/fortune/blob/93bd5d9d1286b4839520a7e2aba26f7f01ac553d/lib/record_type/ensure_types.js#L65

These `denormalizedFields` are being returned in each record, delimited by `__` prefix and suffixes, but if symbols were returned as seen in [constants.js](https://github.com/fortunejs/fortune/blob/master/lib/common/constants.js) these would not be properties of the record and would not need to be checked against record types when iterating over enumerated objects.

We can provide a PR if you'd like, though delimiting seems hard coded in [ensure_types.js](https://github.com/fortunejs/fortune/blob/master/lib/record_type/ensure_types.js) so some guidance would be appreciated here.

**Comment by daliwali** [comment]
No, this is intentional.

Symbols are not serializable. This has many limitations, including not being able to pass update messages between processes.

I will close this for now.
