### ISSUE TITLE
Updating a one to one field across types does not unset previous relation

### ISSUE THREAD

**Issue by acoreyj** [fortunejs/fortune#297]
If there is a one to one relation between types and it is updated to switch the relationship to another entry the original relationship entry will not get an update.

I forked the repo and added a test (which fails) showing the issue. Here is the commit:
https://github.com/acoreyj/fortune/commit/76b646432dd47d367d1d58bf643a0b4f12466834

**Comment by acoreyj** [comment]
@daliwali Any thoughts on this bug?

**Comment by daliwali** [comment]
Apologies, I have been pre-occupied lately. I agree that this is a bug and I'll investigate.

**Comment by daliwali** [comment]
Thanks for the test case, I was able to reproduce the issue and fixed it in this commit: https://github.com/fortunejs/fortune/commit/687499285e5ed4ba880ef249b5898d06a47121dd

Patch version has been published as `5.4.4`.

**Comment by acoreyj** [comment]
@daliwali 

Thanks so much, if you are curious I found this and the indexeddb bug because I'm using Fortune for the database abstraction for automatically generating an graphql API based just on the schema. 

https://github.com/genie-team/graphql-genie

Thanks for creating fortune, saved me a lot of time for sure.

**Comment by daliwali** [comment]
@acoreyj interesting. I had briefly considered writing a GraphQL serializer as an addon for `fortune-http` but I am unmotivated to do that myself. I'm glad that it works, though.
