### ISSUE TITLE
pull update flips order of an array

### ISSUE THREAD

**Issue by acoreyj** [fortunejs/fortune#298]
Hey again @daliwali, 

In my own testing I noticed doing a pull flips the order of an array. I noticed in the [pull file it iterates backwards](https://github.com/fortunejs/fortune/blame/master/lib/common/array/pull.js#L21), along with a comment that it needs to. 

It's probably not a huge deal but it's generally expected that arrays maintain order. Seems the fix would be as simple as iterating forward or changing the push to an unshift

**Comment by daliwali** [comment]
This is a good catch, I haven't really noticed since I haven't had a case in which array ordering mattered, but it is odd behavior regardless. I like `unshift`: https://github.com/fortunejs/fortune/commit/b7cd82078bbb589713484b5cab3676ec24147b20

Patch version released as `5.4.5`.

**Comment by acoreyj** [comment]
@daliwali 

Thanks, yup the only reason I noticed was doing an equality check on a test case.
