### ISSUE TITLE
new Function causes Content Security Policy exception.

### ISSUE THREAD

**Issue by lasersox** [fortunejs/fortune#300]
Due to usage of "new Function", fortune triggers error: `Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy`.

https://github.com/fortunejs/fortune/blob/18c0cf8223fdce025c051ccb0f009004d453c42c/lib/common/message.js#L57

**Comment by daliwali** [comment]
Interesting, I think it shouldn't too difficult to work around that.

**Comment by daliwali** [comment]
Workaround: https://github.com/fortunejs/fortune/commit/4d16df49e16d6ef26be9744de36a6b632491d876

Patch version `5.5.1` published.

**Comment by daliwali** [comment]
Hey @lasersox I am curious, did this occur at compile time? Or did you actually call `message.copy`?

**Comment by lasersox** [comment]
It occurs during application startup. I didn't directly call message.copy.

**Comment by lasersox** [comment]
There's also a new Function in the error-class package imported by fortune.js. Not sure if that one is similarly easy to resolve.

**Comment by daliwali** [comment]
Ok, I resolved all of the CSP issues by testing it out with `Content-Security-Policy: script-src 'self'`.
