### ISSUE TITLE
Polymorphic alternative

### ISSUE THREAD

**Issue by allthesignals** [fortunejs/fortune#301]
It looks like in an [old doc](https://github.com/fortunejs/fortune/blob/d2a9ccfc55720cd1a89ac411d861268f55a2ad6f/doc/CAVEATS.md), polymorphism isn't supported: 

> Polymorphic Associations
> This is not supported and will not be. Just create multiple foreign keys to support linking to different types.

Is there any example of what this would look like? It sounds like you're saying to simple split out a polymorphic association field into multiple fields for each type.

**Comment by daliwali** [comment]
>It sounds like you're saying to simple split out a polymorphic association field into multiple fields for each type.

Yes, that is what it means. This simplifies how relationships work greatly. Polymorphic associations can be implemented in an *ad hoc* way via input/output hooks, I wouldn't really recommend it because the usual queries wouldn't work.

**Comment by allthesignals** [comment]
Okay, sounds good - thanks @daliwali
