### ISSUE TITLE
How to do many-to-many ?

### ISSUE THREAD

**Issue by checkerap** [fortunejs/fortune#305]
I'm trying to model the following, a clinic has many doctors, and doctors belong to many clinics.

  ```
clinic: {  
    name: String,  
    doctors: [ Array('doctor')]  
  },  
  doctor: {  
    name: String,  
    email: String,  
    clinics: [Array('clinic')]  
  }  
```

If i create a clinic, than create doctors with relationships to that clinic, I can only get the clinics from the doctor, not the doctors from the clinic.

Any ideas?

**Comment by daliwali** [comment]
You need to define the inverse field, as stated in the documentation and readme. It's optional to define, but without it, it won't know which relationships are related. In this case it would be:

```js
clinic: {
  doctors: [ Array('doctor'), 'clinics' ]
},
doctor: {
  clinics: [ Array('clinic'), 'doctors' ]
}
```

**Comment by checkerap** [comment]
Thank you, that works, not sure how I missed that.
