### ISSUE TITLE
Cleaning up relationships after delete

### ISSUE THREAD

**Issue by cahva** [fortunejs/fortune#308]
Hi,

If I have relationship like this:

```
user: {
  name: String,
  enemies: [ Array('user') ]
}
```
(I guess that `enemies` field could also be just `Array('user')`)

If I create 2 users, lets say "User 1" and "User 2" and add "User 2" as enemy of "User 1".

| id   | name   | enemies
------|----------|--------
u1    | User 1 | u2
u2    | User 2 | -

If I remove User 2 (id: u2), the relationship will still stay on user 1.

| id   | name   | enemies
------|----------|--------
u1    | User 1 | u2

Problems will start to rise when you try to update fields in u1 as fortune will spit out error:
```
A related record for the field "enemies" was not found.
```
(that comes from lib/request/check_links.js:62:31)

I see that there is the `__user_enemies_inverse` field which is not used in deletion of a record when I checked using debugger.

Is this intended behaviour or is it a bug?

Heres a small example server file what I used to test this:
https://gist.github.com/cahva/666ff9c29b0303e065f64c4fb1a420c1

**Comment by daliwali** [comment]
This is definitely a bug, I don't think hidden inverse fields are thoroughly tested.
