### ISSUE TITLE
Custom Pluralize

### ISSUE THREAD

**Issue by rhettl** [fortunejs/fortune#311]
Hello, 

One of my types is "faculty". In english, I would consider the singular to be "a faculty member" so I am using faculty as both singular and plural. 

I have looked into the inflection library, but there isn't a way to push strings into their "uncountable" array as it is hidden behind a closure. 

How should I tell Fortune that the plural of "faculty" is "faculty", not "faculties"?

**Comment by daliwali** [comment]
Belongs here: https://github.com/fortunejs/fortune-json-api

You want to turn off `inflectType`, see the readme.
