### ISSUE TITLE
`include` param documentation does not match the example

### ISSUE THREAD

**Issue by mattcollier** [fortunejs/fortune#313]
I think it's the case that the prose says that the parameter should be a 3 dimensional array, but the example  shows a 2 dimensional array which omits the second dimension, depth, described in the prose:

https://github.com/fortunejs/fortune/blob/master/lib/index.js#L333-L336

**Comment by daliwali** [comment]
Nope, the prose is correct. To see it more clearly:
```
[['comments', ['author', { ... }]
^^ .                  ^
12                     3
```
