### ISSUE TITLE
Is it possible to export/import fortune dump?

### ISSUE THREAD

**Issue by NtsDK** [fortunejs/fortune#315]
I tried to figure out how to export/import fortune dump but I didn't find this information.
Is it possible?

**Comment by daliwali** [comment]
This is usually handled at a lower level. Most database vendors offer this functionality so there's really no need to handle it here.

https://www.postgresql.org/docs/current/backup-dump.html
https://docs.mongodb.com/manual/reference/program/mongodump/

**Comment by NtsDK** [comment]
For your information - I want to use the same db adapter in both browser and node environment.
All existing adapters are browser specific or node specific except in-memory adapter.
But in-memory adapter has no dump support this moment.

**Comment by daliwali** [comment]
It is really trivial to do.

```js
// Export
const dump = JSON.stringify(store.adapter.db)

// Import
store.adapter.db = JSON.parse(dump)
```

**Comment by NtsDK** [comment]
Thank you)
