### ISSUE TITLE
Delete requires ids array - Documentation says it's optional.

### ISSUE THREAD

**Issue by hamez0r** [fortunejs/fortune#318]
https://github.com/fortunejs/fortune/blob/d0dfe10c53d06600eb6e820f746745daf511a711/lib/request/delete.js#L58

^ This line will throw an error. Is there any option for removing all elements of a collection?

**Comment by daliwali** [comment]
`adapter.delete()` has no ID restriction and is expected to drop everything.
http://fortune.js.org/api/#adapter-delete
