### ISSUE TITLE
What is the recommended way to perform queries? store vs store.adapter

### ISSUE THREAD

**Issue by hamez0r** [fortunejs/fortune#319]
I can't figure out what the way this library is intended to be used. I see there's documentation on the Fortune object (the store), although most of the methods are wrappers around adapter methods.

However, the expectation would be the wrappers work as well. I'm not sure if that's not the case, or if I'm doing something wrong here.

For example, take the `update` method. The Fortune and the Adapter methods have the same required parameters: `type` and `updates`. Since documentation doesn't mention whether parameter types should be different, the assumption is they are the same.

This call, however:
```javascript
  const result = await store.update('user', [{
    id: user.id,
    replace: { 
      email: email,
      password: password
    }
  }]);
```
will not update the records in the database. This one, will perform the operation correctly:
```javascript
  const result = await store.adapter.update('user', [{
    id: user.id,
    replace: { 
      email: email,
      password: password
    }
  }]);
```

Please let me know if I'm doing something terribly wrong here.
The question still remains. What object should be asked to perform (most of) the work? Fortune, or Adapter?

Thanks!

**Comment by daliwali** [comment]
Hi @hamez0r ,

Which adapter are you using? It's intended to use the wrapper methods, not the adapter directly. 

Calling the adapter directly will bypass a lot of functionality:

- Using database transactions for a request (especially for Postgres)
- Using input/output hooks
- Bi-directional relationship updates

The adapter is exposed mainly as an escape hatch.

**Comment by hamez0r** [comment]
Hi @daliwali, thanks for your reply. I am using the Mongo adapter.

So for the 2 examples above, the first one is intended to be used, correct? However `store.update` doesn't see to perform the desired functionality. Not sure whether the store is the problem, or the adapter.

Any advice you could give?

Thanks!

**Comment by daliwali** [comment]
You probably need to figure out what the error is first on your side first before I can help you.

```js
try {
  const result = await doSomething(...)
} catch (error) {
  console.error(error)
}
```

**Comment by hamez0r** [comment]
That's the thing, there is no error. It looks like it won't perform the update.

Take this snippet of code:
```javascript
  console.log(JSON.stringify(user))
  console.log(`Update: email: ${email}, password: ${password}`);

  const result = await store.update('user', [{
    id: user.id,
    replace: { 
      email: email,
      password: password
    }
  }]);

  console.log(JSON.stringify(result));

  const { payload: { records: [ sameUser ] } } = await store.find('user', [id]);
  console.log(JSON.stringify(sameUser));
```
It will produce the following output:
```
{"id":"97c2607a-a295-4f86-b6b5-fb665c4f32d1","email":"regular@domain.com","password":null,"access":"regular"}
Update: email: new@domain.com, password: $2b$10$FtxQoBvrhgVqRgSNCF1GpuFyDtfpfl1ViLFjtqaEbZzGqZqwa//Xa
{"meta":{"updateModified":true},"payload":{"records":[{"id":"97c2607a-a295-4f86-b6b5-fb665c4f32d1","email":"regular@domain.com","password":null,"access":"regular"}]}}
{"id":"97c2607a-a295-4f86-b6b5-fb665c4f32d1","email":"regular@domain.com","password":null,"access":"regular"}
```

The email will continue to be 'regular@domain.com', although I'm trying to set it to 'new@domain.com'.

As I mentioned before, doing the same via `store.adapter.update` does the job. The problem is when I'm trying to use 'store.update'.

**Comment by hamez0r** [comment]
Found the issue, the hook was returning the object when a request was made.
