### ISSUE TITLE
CORS enabling not working?

### ISSUE THREAD

**Issue by alexbfree** [fortunejs/fortune#62]
Not sure if I am doing something wrong, but I can't seem to enable CORS.

My fortune API looks like this (CoffeeScript/Node.JS):
```
argv = require("minimist")(process.argv.slice(2))
API = require("fortune")
if argv._.length == 0
  console.log "Usage: node API.js <port>"
else
  port = argv['_'][0]
  app = API(db: "user-event-log", cors:true).resource("event",
    time: Date
    subject_id: String
    user_id: String
    type: String
  ).listen(port)
  exports.API = API
```

My dependencies from `package.json` are:
```
  "dependencies": {
    "coffee-script": "^1.8.0",
    "fortune": "^0.2.4",
    "i": "^0.3.2",
    "minimist": "^1.1.0"
  },
```
When I launch with `node API.js 8080` and GET `http://localhost:8090/events`, I do not see the `Access-Control-Allow-Origin:*` header in the response:

```
Date: Fri, 30 Jan 2015 16:22:02 GMT 
Content-Type: application/vnd.api+json; charset=utf-8 
Content-Length: 378 
ETag: W/"17a-679725808" 
``` 

Am I doing something wrong or is this a bug?

**Comment by daliwali** [comment]
Ahh, probably a bug >__<
If it screws up I would recommend just using a [separate library for CORS](https://www.npmjs.com/package/express-cors).

**Comment by alexbfree** [comment]
Thanks! How would I integrate this with fortune?

On Friday, January 30, 2015, Dali Zheng <notifications@github.com> wrote:

> Ahh, probably a bug >__<
> If it screws up I would recommend just using a separate library for CORS
> <https://www.npmjs.com/package/express-cors>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/daliwali/fortune/issues/62#issuecomment-72245080>.
>


-- 
Alex Bowyer - alex.bowyer@gmail.com - @alexbfree
<http://www.twitter.com/alexbfree>
Interaction Designer, Citizen Scientist, Web Developer

alexbowyer.com
<http://alexbowyer.com/?utm_source=alex&utm_medium=emailsig&utm_content=homepage&utm_campaign=none>
 - Blog <http://blog.alexbowyer.com/> - WeReddit Podcast
<http://www.wereddit.com/?utm_source=alex&utm_medium=emailsig&utm_content=homepage&utm_campaign=none>
 - Zooniverse <http://www.zooniverse.org/>

**Comment by daliwali** [comment]
Something like:
```js
app.router.use(cors);
```
`router` is actually an express instance.
