### ISSUE TITLE
Fortune crashes on post (postman form-data)

### ISSUE THREAD

**Issue by marktheis** [fortunejs/fortune#64]
I'm trying to do a post via postman and if the form-data tab in postman is selected fortune crashes and I get this in the terminal `TypeError: Cannot read property 'split' of undefined`.

My app looks like this.
```
var fortune = require('fortune');

options = {
  adapter: 'nedb',
  host: 'localhost',
  flags: {
    inMemoryOnly: false,
    filename: 'data.db',
    autoload: true
  }
};

var app = fortune(options);

app.resource('item',{
  name: String
});

app.listen(1337);
```
The database is being created when I post.

What am I doing wrong and how would I do a post in postman?
Thanks.

**Comment by daliwali** [comment]
This is probably due to the massive discrepancy between the latest JSON API spec and the current `0.2.x` version. I am not maintaining `0.2.x` in favor of getting 1.0 alpha out as soon as possible, which will feature modular serializers so that it is not so closely coupled with any spec, and also it will delegate JSON API specific issues to that serializer.

**Comment by marktheis** [comment]
Okay. So do you recommend that I switch to the rewrite branch or is that not functional?
I'm building a very simple read-only api with fortune and plan to only create users with a script. So I don't need all the features of fortune. Only the GET part and that it not crashes on POST :)

And great project btw. I really like your take on this. It's very easy to use and understand.

**Comment by daliwali** [comment]
Honestly it is not good timing to use this project right now, as I am still working on the rewrite branch. 
I am devoting most of my free time on open-source while I am currently a full-time student so progress is moving along. 

For your purposes, it may be better to use koa/express and a db driver and handle request/response manually.

**Comment by marktheis** [comment]
I will look at the other options then and keep my eyes on this.
If you need a volunteer to help with front-end/web design feel free to hit me up.
