### ISSUE TITLE
Support easier contributions for Windows users

### ISSUE THREAD

**Issue by dcherman** [fortunejs/fortune#71]
Would you accept a pull request that transitioned the stuff that's currently done in the `Makefile` to use Gulp?  Alternatively, I could write a node script that would execute the same commands as make, but in a cross platform manner.

Currently you can't actually build the project on Windows easily due to command and path separator differences.  In order to get it working, I ended up installing a bunch of GnuWin32 utilities and modifying the Makefile

**Comment by daliwali** [comment]
Hmm, perhaps just a package.json based build would be possible.

**Comment by dcherman** [comment]
Since the scripts in `package.json` are just executed as shell commands, they still wouldn't be portable across platforms.  I'm happy to write a Gulp based build if you'd like, or I can write individual scripts and make `npm run build` just do the right thing.  Depends on what you'd accept.

**Comment by daliwali** [comment]
Oh, I am not aware of how Windows environments work. Mainly the Makefile is used for testing and prepublishing, and even for testing it is avoidable by running `babel-node test`.

**Comment by daliwali** [comment]
I removed the Makefile and replaced it with a bunch of scripts in `package.json` that should work on Windows, let me know if it doesn't.

**Comment by dcherman** [comment]
I gave it a test run this morning and everything looks like it runs on my Windows box.  Thanks!
