### ISSUE TITLE
Accessing raw request/headers in Adapters

### ISSUE THREAD

**Issue by dcherman** [fortunejs/fortune#72]
Is there a publicly supported manner of getting access to a given request's headers somewhere such that I can access them or pass them along to a custom adapter?

My use case is that I have an adapter that will be talking to another web service rather than a database directly.  To support that, I'll need to pass along authentication data for the current request to that web service

*Edit I should mention that I'm working against the `rewrite` branch

**Comment by daliwali** [comment]
Not in the adapter, but in the serializer's `processRequest` and `processResponse` methods.
