### ISSUE TITLE
Create new adapter during runtime

### ISSUE THREAD

**Issue by TheHandsomeCoder** [fortunejs/fortune#73]
Hi All,

Is it possible to change the adapter during runtime? For example having a resource available at ~/resource1, but after calling a function change for the adapter to point at ~/resource2.

Is this possible or would a new instance of Fortune need to be created?

Cheers

Scott

**Comment by daliwali** [comment]
You can call `stop`, instantiate your own adapter under `this.adapter`, and call `start` again, but why complicate things? Maybe it would be better to just have two instances, can you explain the use case?
