### ISSUE TITLE
How to create unique fields?

### ISSUE THREAD

**Issue by jlcarvalho** [fortunejs/fortune#74]
Hi, how can I create an unique field?
I did not found anything about this in the documentation.

**Comment by daliwali** [comment]
That is outside of the scope of Fortune for the foreseeable future, and would have to be implemented by the specific adapter. An idea is that it could be defined on a field like this:

```js
{ type: String, unique: true }
```

Then the adapter can look for this `unique` key in the field definition, and create a unique index during the `connect` method.
