### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by ghwilson4456** [fortunejs/fortune#76]
I'm playing around with Fortune 1.0.0-alpha.9 and Ember. Ember's on port 4200 and Fortune is on port 1337; both on localhost. The browser is reporting "'No Access-Control-Allow-Origin' header is present ..." and I see no options for CORS support or custom headers. Any advice?

**Comment by daliwali** [comment]
Fortune doesn't handle CORS, the `http` module is only concerned with content negotiation and response. I would recommend using any of the fine CORS options for Node.js:

- https://www.npmjs.com/package/cors
- https://www.npmjs.com/package/koa-cors
- http://hapijs.com/api (config option for CORS)

There may be other goodies that you might need, such as ETag support, compression, etc, that is much better supported by other modules.
