### ISSUE TITLE
Update resources returns error 500

### ISSUE THREAD

**Issue by jlcarvalho** [fortunejs/fortune#79]
The following request returns error 500:

`PATCH /ingresso/611c95257c4c89d2e72e6919fea62998 HTTP/1.1`
`Content-Type: application/vnd.api+json` 
`Accept: application/vnd.api+json`

```json
{
  "data": {
    "id": "611c95257c4c89d2e72e6919fea62998",
    "type": "ingresso",
    "attributes": {
      "name": "Primeiro Lote..."
    }
  }
}
```

The result:

```json
{
    "errors": [
        {
            "name": "Error",
            "detail": "An internal server error occured."
        }
    ]
}
```

**Comment by daliwali** [comment]
Hmm, can you attach a `catch` handler to the http function?

```js
fortune.net.http(app).catch(error => console.log(error.stack))
```

It doesn't provide logging by default, I'd like to see what the error is.

**Comment by daliwali** [comment]
By the way, in `alpha.10` the default error that you get for inputs is more appropriate, it will return a `BadRequestError` (400) with the message "The request is malformed."
