### ISSUE TITLE
Please do not clean git history

### ISSUE THREAD

**Issue by ninjatronic** [fortunejs/fortune#80]
From NPM:

![screen shot 2015-06-14 at 12 11 16](https://cloud.githubusercontent.com/assets/4722391/8148291/8538d454-128e-11e5-81d9-69819390d1a4.png)

But no releases are tagged in Github and none of the old code is in the tree. :( It is useful to see, especially if maintaining things built with the old versions, or updating from old to new etc.

Thanks

**Comment by daliwali** [comment]
I don't think releases are worth tagging until post-1.0 when it is stable. There are some anticipated breaking changes.

also, none of the history is erased actually. every commit since 0.0.1 is in the history. all of the pre-1.0 releases are in npm.

**Comment by ninjatronic** [comment]
They're not visible in Github...

![screen shot 2015-06-14 at 14 22 25](https://cloud.githubusercontent.com/assets/4722391/8148702/d1b61640-12a0-11e5-92ad-ec8f4edad677.png)

It's useful to be able to go back and read examples from previous releases, for example. W/e really, jsut a thought. :)

**Comment by daliwali** [comment]
in npm, not github. for sure releases will be tagged in github after 1.0 :)
