### ISSUE TITLE
PATCH fails due to plural type in relationship

### ISSUE THREAD

**Issue by nickschot** [fortunejs/fortune#86]
I have some very simple models with a hasMany relationship:

```
store.defineType('person', {
    name: { type: String },
    items: { link: 'item', inverse: 'person', isArray: true }
}

store.defineType('item', {
    name: { type: String },
    person: { link: 'person', inverse: 'items', isArray: false }
}
```

I create these records with ember/ember-data 1.13.5. This goes fine. But when adding the relationship by adding the person to item in ember-data, the PATCH request to fortune fails with the following message:
`Data object field "$(reservedKeys.type)" is invalid, it must be "$(relatedType)".`

After some debugging the problem seems to be that fortune wants the "type" of the person relationship added to item to be "person", while ember-data sends "persons". During the creation of both records, all types were plural too. The JSON API itself seems agnostic about whether types should be plural or not.

**Comment by 0x8890** [comment]
@nickschot thanks for reporting! Not sure if it might be a problem with how Ember Data handles string inflections, or Fortune. in any case the plural of "person" is not "persons" but "people". will investigate.

**Comment by nickschot** [comment]
Thanks! I'll check it out. The model names I'm actually using in my application do end with -s in this case, my bad on the "persons".

**Comment by nickschot** [comment]
Some more findings.

If I change the singularize on this line: https://github.com/fortunejs/fortune/blob/master/lib/serializer/serializers/json_api/index.js#L396 into a pluralize, it fixes the issue. The value `fields[field][keys.link]` (which is the type) already is a singular before it looks if it needs to be singularized. 

I'm not all that familiar yet with fortune and the json-api standard, so I'm not sure if what I am doing is correct. Hope it helps.

**Comment by 0x8890** [comment]
@nickschot I think you are right. Also [this line](https://github.com/fortunejs/fortune/blob/master/lib/serializer/serializers/json_api/index.js#L325) may have the same issue as well.

If you'd like to make a PR for this I'd appreciate it, otherwise I can fix this.

**Comment by nickschot** [comment]
Hah, same idea! I'll make a PR somewhere during this evening!

**Comment by 0x8890** [comment]
:+1:
