### ISSUE TITLE
Date type not put into JSON correctly

### ISSUE THREAD

**Issue by nickschot** [fortunejs/fortune#89]
A field with a Date type ends up in the JSON unusable like:
`created: Sun Jul 19 2015 21:09:59 GMT+0200 (CEST)`

This should most likely be a String containing an ISO 8601 date. Can of course be easily worked around with an output transform, but should be an easy fix.

**Comment by 0x8890** [comment]
Wait, are you sure? In running the tests, the dates are already formatted ISO 8601. Can you try to run:

```js
$ babel-node test/integration/serializers/json_api.js
```

There is a field `birthday` that you should look out for since it's a Date object. Also can you tell me what Node / platform you're using?

**Comment by nickschot** [comment]
The test seems to work fine. I'm using Node 0.12.7 with MongoDB. Investigating some more...

**Comment by 0x8890** [comment]
Are you sure it's not PEBCAK? It's easy to get confused by that, if you try `console.log(new Date())` it will call `Date.prototype.toString` and you get that format in the terminal, but `JSON.stringify(new Date())` will actually return an ISO 8601 string.

**Comment by nickschot** [comment]
Indeed it seems to work fine. Must have been a PEBCAK indeed. Sorry!

**Comment by 0x8890** [comment]
No problem :)
