### ISSUE TITLE
filtering, sorting, pagination

### ISSUE THREAD

**Issue by daliwali** [fortunejs/fortune#9]
Query-string syntax to filter, sort, and paginate. Example:

```
?filter={"name":"daliwali"}&sort={"age":1}&page=1
```

The `findMany` method in the adapter already supports finding resources by arbitrary queries, but pagination might be tricky.

**Comment by alexbfree** [comment]
is this filtering implemented? Or is this just an idea? I don't think I can use fortune in my application without filtering (and pagination)

**Comment by Cryrivers** [comment]
Yeah same question as OP. Is there any plan to implement filter, pagination and sort? As far as I know, JSON API spec is about to be finalized. It would be a great time to implement such things.
