### ISSUE TITLE
TypeError: The serializer must be a function or class.

### ISSUE THREAD

**Issue by TheHandsomeCoder** [fortunejs/fortune#95]
Looking at some snippets given in other issues I attempted to pass options to the fortune.create() function as follows

```javascript
import fortune from 'fortune'
import http from 'http'

const store = fortune.create({
  serializers: [ {
    type: fortune.serializers.jsonApi,
    options: {
      obfuscateURIs: false // Tell the serializer to add a prefix to the hyperlinks.
    }
  } ]
})


const listener = fortune.net.http(store)

store.defineType('user', {
  name: { type: String },
  groups: { link: 'group', inverse: 'members', isArray: true }
})

store.defineType('group', {
  name: { type: String },
  members: { link: 'user', inverse: 'groups', isArray: true }
})

const server = http.createServer(fortune.net.http(store))

store.connect().then(() => server.listen(1337))
```

However when I try to start the server I get the above error. Am I setting up fortune incorrectly or is there something I've missed? I can't seem to find examples on the github page or within the documentation

**Comment by 0x8890** [comment]
Can you show the error you're getting? One thing that stands out is that the name of the serializer is wrong, I renamed it so that it's `JSONAPI` instead of `jsonApi` now.

**Comment by TheHandsomeCoder** [comment]
Yup that would have been helpful 

`[ 'MicroAPI', 'JSONAPI' ]`

Changed it to JSONAPI and removed the options and that solved it :)
