### ISSUE TITLE
Cast query parameters to defined types

### ISSUE THREAD

**Issue by jgornick** [fortunejs/fortune#98]
I am running into an issue where I have a field in my type called "number" that is a type of "Number". However, when I include number in a query parameter ```?filter[number]=188```, a string of "188" is passed to the adapter. In my case I'm using the MongoDB adapter which won't filter number fields as a string (e.g. ```db.getCollection(type).find({ number: '188' })``` vs ```db.getCollection(type).find({ number: 188 })```). Another example is providing a filter value as a string with spaces: ```?filter[title]=The title of the entity``` which is translated to a query parameter as ```{ title: "The+title+of+the+entity"}```.

It felt more natural to put the casting of query parameters in this project rather than the adapter project. I am also using the JSON API serializer.

This also brings up the need to allow nested objects to be define when defining a type because in my case some nested object values are mixed.

**Comment by 0x8890** [comment]
Good point, this is something which should probably be handled in the serializer, as that is where the query string is parsed. 

I think that the spaces issue is client-side due to not properly URI encoding the query, i.e. the space should be encoded as `%20`.

**Comment by 0x8890** [comment]
Fixed in 84bb00c58a006e03ca759e82f1f4e6140c5589d1, published as `1.0.0-beta.35`.
