### ISSUE TITLE
null is invalid as date value

### ISSUE THREAD

**Issue by nickschot** [fortunejs/fortune#99]
Since https://github.com/fortunejs/fortune/commit/3ef295e7b69e2c0aefd04e56e6398613cefe4ef1 it is not allowed to send a null value along as a date. Is this intentional? I can't find in JSON API if it's allowed or not for attributes.

**Comment by 0x8890** [comment]
Oops, it was intentional but not quite what I had intended. It should be allowed to set any field as `null` by default. The existing check could be modified somehow, PR is welcome.

**Comment by 0x8890** [comment]
Resolved in commit 1bd04437a0965ea0c53ce829f37d451478ee2808.
